### ISSUE TITLE
Add styles for blockquotes

### ISSUE THREAD

**Issue by mansona** [mainmatter/mainmatter.com#1020]
I don't know if it's just my writing style 😂 but I have a tendency to like using blockquotes in posts. When I was writing my blog post this month I noticed that the new design doesn't have any designs for blockquotes at all.

- they are not visually different from other text (no colour changes or italics)
- they are not indented
- they seem to be missing normal paragraph padding/margins
- there are no visual highlights (like a vertical bar)

Here is an example of what I had in mind (taken from [my own blog](https://chris.manson.ie/the-true-power-of-json:api-have-someone-else-do-it/) which is using Ghost's Casper default styles)

![Screenshot 2020-03-25 at 17 08 36](https://user-images.githubusercontent.com/594890/77564925-5f000d00-6ebb-11ea-8546-d999ff046088.png)

**Comment by marhigh** [comment]
The design for this is ready to go: https://share.goabstract.com/37b460bf-0b64-46be-bc12-6149801017c4

Adds a stylized blockquote for both large and small viewports. This block quote uses a new, simplified spacing system that we will slowly transition the website to: 2px, 4px, 8px, 16px, 32px, 64px and 128px. The simplified spacing helps us be more consistent with our design.

This task includes four styles:

1. Default desktop for viewports >888px. It can be found in a normal blog post excerpt (blog index), and in the body of a blog post. This has a top & bottom margin of 64px.
2. Default mobile for viewports <887px. It can be found in a normal blog post excerpt (blog index), and in the body of a blog post. This has a top & bottom margin of 32px.
3. A loud desktop style, used for the featured blog excerpt in viewports >888px. This has a top & bottom margin of 32px.
4. A loud mobile style, used for the featured blog excerpt in viewports <887px. This has a top & bottom margin of 32px.

The font size of the quote always matches the body font size that surrounds it, and its responsive behavior also matches that. The square part of the quotation mark matches the x-height of the body font size that surrounds it and is aligned to the baseline of the first line of text.

**Comment by marhigh** [comment]
Closing this issue, since it is covered in https://github.com/simplabs/simplabs.github.io/pull/1260
