### ISSUE TITLE
Update Page Titles and Page Meta Descriptions 

### ISSUE THREAD

**Issue by arthurp1** [mainmatter/mainmatter.com#1025]
Here's a list of all the pages that need their page title and meta descriptions updated. The goal is to improve the click-through-rates of our pages when they show up in organic search results.

PageDigitalProducts
title: Digital Product Delivery | Service | simplabs
description: Our team of experts delivers everything from ideation to design and engineering. We can turn any idea sketched on the back of a napkin into a stable, shipped product.

PageElixirExpertise
title: Level-up your team with Elixer/Phoenix experts | simplabs
description: Augment your in-house team with web technology experts. Speed up projects and remove long-standing issues - from refactoring to shipping new features.

PageEmberExpertise
title: Augment your team with top Ember.JS experts | simplabs
description: Temporarily extend your team with experts that are Ember core-team contributors. Speed up projects and remove long-standing issues - from refactoring to shipping new features.

PageHomepage
title: simplabs - Digital Product Agency.com
description: We are Europe’s leading Mobile and Web Design & Development Agency. Our clients value code quality, dependability and honesty. We are trusted by Generali, Qonto, Trainline, and Clark.

PageProductDesign
title: Product Design | Service | simplabs
description: Great product design is what makes digital products tick. Research, rapid prototyping and testing turn a vision into remarkable experiences for mobile and web.

PageProductDevelopment
title: Product Development | Service | simplabs
description: We are Europe’s leading web development experts. We obsess over crafting the absolute best products we can, built on architectures that are easy to extend, update and maintain. 

PageServices
title: Our Services - Building Better Products
description: We turn ideas into digital products - from concept to development. We also help engineering teams to work better through Team Augmentation and Tutoring. 

PageTeamAugmentation
title: Team Augmentation | Service | simplabs
description: We help teams ship and become more effective. Our technology experts merge with your in-house teams to ensure timely and high quality delivery of large-scale projects. 
PageTrainingAndSupport

PageTrainingAndSupport
title: Training | Service | simplabs
description: We help engineering teams to be more effective through Tutoring, Workshops, Code Reviews & Audits. Our engineers are famous for their Ember.js, Ruby on Rails & Elixir/Phoenix expertise.

PageWhySimplabs
title: Why simplabs - Europe’s Leading Web Experts
description: We are known for digital experiences that are clean, dependable, and architected for scale. Our open-source contributions are relied upon by firms like LinkedIn, Heroku, Twitch & more.

PageWork
title: Our Work - How we helped ship world-class Web & Mobile Apps | simplabs
description: A proven track record of building mobile and web apps for Europe’s fastest growing start-ups and big enterprises – covering everything from design to code. 

Blog
title: Product & Engineering Blog | simplabs
description: The latest insights on product strategy, design and development. Read in-depth articles on the web technologies we master: Ember.js, Elixir/Phoenix, and JavaScript.

Talks
title: Talks, Workshops & Podcasts | simplabs
description: We value sharing our expertise. Watch 30+ videos. From Product Design to Engineering. Global events include: JSConf, EmberFest, ReactiveConf, and many more.

**Comment by arthurp1** [comment]
@marcoow Is the issue complete like this? Could you assign someone?

**Comment by marcoow** [comment]
Yes, it's fine. Someone will self-assign it when they have the time
