### ISSUE TITLE
Add Announcement for International JavaScript Conference Munich

### ISSUE THREAD

**Issue by jayjayjpg** [mainmatter/mainmatter.com#112]
"Learn more":  https://javascript-conference.com/en/

23.10 - 27.10. 2017

Afaik there will be both a simplabs booth and a talk presented by us. More on the talk on here: https://javascript-conference.com/web-development-architecture/a-glimmer-of-hope-creating-modern-web-components-with-glimmer-js/

**Comment by marcoow** [comment]
Text:

```html
<h4>Meet us at iJS in Munich</h4>
<p>The international JavaScript Conference will take place in Munich, Oct. 23rd to 27th. <strong>Be sure to stop by our booth</strong> for info on Ember.js and Glimmer (and some swag as well)!</p>
<a href="https://javascript-conference.com/en/" class="custom-button">learn more</a>
```

<img width="542" alt="bildschirmfoto 2017-09-14 um 22 06 56" src="https://user-images.githubusercontent.com/1510/30453391-0c868db4-9999-11e7-963a-8dd845a207b5.png">


@jessica-jordan, @oliverbarnes, @geekygrappler: text ok?

**Comment by oliverbarnes** [comment]
👍

**Comment by jayjayjpg** [comment]
Sounds good, I like the swag teaser 👍
