### ISSUE TITLE
Add call to action to workshop pages

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#113]
We should have a call to action on the workshop pages for contacting us, e.g. on https://simplabs.com/training/2016-12-19-ember-cli-basics.html

@ninaarndt might have ideas for where to add it and how it could look.

**Comment by marcoow** [comment]
I think we need to do this before it makes sense to continue running the Twitter ads. This should be done before the case studies.

**Comment by ninaarndt** [comment]
![workshop contact us](https://user-images.githubusercontent.com/1510/28664612-49f1c0b4-72c1-11e7-951d-d545dd341259.png)

**Comment by marcoow** [comment]
Maybe we should remove the elixir workshop ad as that might be confusing?
