### ISSUE TITLE
Typo on playbook page

### ISSUE THREAD

**Issue by niklaslong** [mainmatter/mainmatter.com#1151]
![Screenshot 2020-06-15 at 09 48 23](https://user-images.githubusercontent.com/13221615/84631519-0bf78e00-aedd-11ea-9cd9-300c9b4155b9.png)

I think this should read: *We believe the classic project manager role **is** an organisational anti-pattern and advocate for self-organised project teams.* (instead of *in*)?

**Comment by marcoow** [comment]
Ouch, indeed 👍
