### ISSUE TITLE
Add EmberFest announcement

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#124]
Once APICON is over we should add an EmberFest announcment instead of it. Ping me for announcement text.

**Comment by marcoow** [comment]
@EmanuelaTrabaldoLena: we should publish this on Sep 20th.

**Comment by marcoow** [comment]
Text:

```html
<h4>Meet us at EmberFest 2017</h4>
<p>simplabs will be at <strong>EmberFest 2017 in Berlin, on October 12th and 13th</strong>. We are looking forward to a great event and a chance to meet up with the European Ember community!</p>
<a href="https://emberfest.eu" class="custom-button">learn more</a>
```

<img width="537" alt="bildschirmfoto 2017-09-14 um 22 01 54" src="https://user-images.githubusercontent.com/1510/30453207-62cf3f3c-9998-11e7-8bc5-90b57b235f1f.png">

@oliverbarnes, @geekygrappler: text ok?

**Comment by jayjayjpg** [comment]
Looks good, I think there's just a minor typo here: 
~~european~~ European

**Comment by marcoow** [comment]
Hm, wouldn't _"European"_ actually be wrong though?

**Comment by jayjayjpg** [comment]
You mean semantically wrong, correct? Imho something like 

> and a chance to meet with the Ember community from Europe and beyond

or similar might work. 
I like the idea to highlight that it's a conference featuring mostly European speakers and attendees, but you're right that it would be correct to mention that it's not a conference restricted to people from Europe either.

**Comment by marcoow** [comment]
I mean grammatically wrong because _"european"_ is an adjective.

**Comment by jayjayjpg** [comment]
In English, adjectives related to people, countries, names, languages, etc. ("Eigennamen") are always capitalized, no? I just looked it up here as well and it seems the lowercase variant is sometimes used, but capitalization is more common and should be preserved:

> In English, adjectives derived from proper nouns (except the names of characters in fictional works) usually retain their capitalization
– e.g. a Christian church, Canadian whisky, a Shakespearean sonnet, but not a quixotic mission, malapropism, holmesian nor pecksniffian.

from [the Wikipedia entry on Capitalization](https://en.wikipedia.org/wiki/Capitalization#Adjectives)

And there is also a similar [question asked here](https://english.stackexchange.com/questions/381/when-should-the-word-english-be-capitalized)

**Comment by marcoow** [comment]
Oh wow, wasn't aware of that. @oliverbarnes: didn't you correct this kind of capitalization in the past to lowercase?

**Comment by oliverbarnes** [comment]
I don't think so, not if I was in my right mind :) `European` should be capitalized, as weekdays, and some others. I lowercase stuff like `software engineering`, `engineer`

Thanks for capitalization rules @jessica-jordan, I've been revising out of my own faulty head and it's much better to have a guide :)

**Comment by marcoow** [comment]
So adjectives derived from nouns are capitalized but actual nouns like _"engineer"_ are not?

**Comment by oliverbarnes** [comment]
[Adjectives derived from proper nouns](https://en.wikipedia.org/wiki/Proper_adjective) (and proper nouns themselves)

`engineer` is a common noun, in English at least. `software engineering` as well, unless it's the name of a course for instance. 

[from miss Julie](https://forum.wordreference.com/threads/civil-engineering-or-civil-engineering.2298787/) 

and examples in https://en.wikipedia.org/wiki/Engineer

**Comment by marcoow** [comment]
So there is an official difference between a _"proper"_ and a _"common"_ noun?

**Comment by oliverbarnes** [comment]
Yes :) https://en.wikipedia.org/wiki/Proper_noun#Common_and_proper_nouns

**Comment by marcoow** [comment]
Wow. As this is obviously far beyond me, please correct the text as you think @jessica-jordan and @oliverbarnes 🙂

**Comment by oliverbarnes** [comment]
https://giphy.com/search/mind-blown

**Comment by oliverbarnes** [comment]
and it's **on October 12th and 13th** (not **at**)

where should I edit?

My girlfriend does text revision at friendly rates, btw =D

**Comment by marcoow** [comment]
you should be able to edit the issue text at the top?

**Comment by oliverbarnes** [comment]
done
