### ISSUE TITLE
Introduce max-content-width

### ISSUE THREAD

**Issue by marhigh** [mainmatter/mainmatter.com#1319]
In order to improve the stability of how the website behaves in larger viewports, let's introduce a maximum content width. 
These ensure that the content doesn't expand endlessly, and helps improve readability of paragraphs through a reduction of the line length. 

Maximum content-width will be set to 1180px with a safe zone on each side of 32px. **Due to it's effect on some of the odd shapes of the website, let's pair up when introducing these containers.** 

The home page is a rough example of how the content-width containers are meant to work. In combination with the introduction of max-font sizes (https://github.com/simplabs/simplabs.github.io/issues/728), these should ensure more stability and better readability of the content in large viewports. 

| Home page (live) at 1920px width | Home page (with max-content-width) at 1920px width |
|----------------------------------|----------------------------------------------------|
|![home_1920px](https://user-images.githubusercontent.com/8226112/95858066-c8167780-0d5c-11eb-9d64-1ea9cfd3a39c.png) | ![home_1920px_withContentWidth](https://user-images.githubusercontent.com/8226112/95858045-c351c380-0d5c-11eb-9d86-888303bfef68.png) |

These are also visible on Abstract: https://share.goabstract.com/024b6053-286d-42cc-a09b-046f8fc0c69f

**Comment by marcoow** [comment]
@marhigh I suggest we don't do this for now. It'd be relatively complex to get it working with new browsers as well as the old one that Percy uses to render screenshots. I believe the way we're handling widths currently doesn't really work (cc @pich) and I think as we assume we'll be changing the website layout anyway with new name/logo etc. it doesn't make much sense to spend a lot of time on this now.

**Comment by marhigh** [comment]
@marcoow does not doing this include not checking https://github.com/simplabs/simplabs.github.io/pull/1370?

**Comment by marcoow** [comment]
Yes – I might have just figured out a simple solution though.
