### ISSUE TITLE
Styling quirks with quotes

### ISSUE THREAD

**Issue by pangratz** [mainmatter/mainmatter.com#160]
https://simplabs.com/training/ then `Ember Data Basic` (https://simplabs.com/training/2016-12-17-ember-data-basics.html):

<img width="1103" alt="screen shot 2017-11-22 at 17 51 02" src="https://user-images.githubusercontent.com/341877/33139616-1b41c99a-cfae-11e7-8b65-dc5ce89c3702.png">

**Comment by marcoow** [comment]
@trabaldini: can you update the course's markdown so that these texts are not blockquotes? Maybe re-run the script that updates the courses based on the data from @mike-north's website anyway - we haven't done that in a while.
