### ISSUE TITLE
Add announcement: Bulgaria Web Summit Conference

### ISSUE THREAD

**Issue by jayjayjpg** [mainmatter/mainmatter.com#169]
This might be good to be added to the website in spring next year

Date: April 14, 2018
Talk Title: Testing against Time in JavaScript Applications
Conference Website: https://bulgariawebsummit.com/

**Comment by marcoow** [comment]
@jessica-jordan: can you ask them to put the simplabs logo under your name as some other speakers have their company logos as well on https://bulgariawebsummit.com?
