### ISSUE TITLE
Underline of links doesn't behave correctly

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1843]
Sometimes the underline of links doesn't seem to behave correctly yet.

It either shows only after a delay:

https://user-images.githubusercontent.com/1510/185214231-5ab523ee-78fa-4bcf-985a-21f056cf3b5b.mov

or when losing hover, fades out and then pops in again:

https://user-images.githubusercontent.com/1510/185214294-c269144e-e5a9-4184-8c6e-e16de144ad62.mov
https://user-images.githubusercontent.com/1510/185214305-25615650-94ad-4a4b-b10c-b811f0f246ab.mov

**Comment by marianneciara** [comment]
This is ready for review, [preview link](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app).

**Comment by marcoow** [comment]
> or when losing hover, fades out and then pops in again:
>
> https://user-images.githubusercontent.com/1510/185214294-c269144e-e5a9-4184-8c6e-e16de144ad62.mov
> https://user-images.githubusercontent.com/1510/185214305-25615650-94ad-4a4b-b10c-b811f0f246ab.mov

This still seems to be the same?

**Comment by marianneciara** [comment]
OK I think I've caught them all this time – apologies! Seems to be a Safari-specific bug. Ready for review: [preview link](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app).
