### ISSUE TITLE
Order on the services submenu should be changed

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1844]
This should be

* Team Augmentation & Training
* Digital Products & Design
* Workshops

<img width="1511" alt="Bildschirmfoto 2022-08-17 um 20 22 58" src="https://user-images.githubusercontent.com/1510/185214620-02359ba2-b6ab-48d6-8e04-e0898fd0a685.png">

**Comment by marianneciara** [comment]
This is ready for review, [preview link](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app).
