### ISSUE TITLE
1px border between elements

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1846]
Some elements seem to have a 1px border between them, e.g.:

<img width="1511" alt="Bildschirmfoto 2022-08-17 um 20 26 22" src="https://user-images.githubusercontent.com/1510/185215409-e9f2f911-fdd0-413e-bba3-2ebc29a97988.png">

<img width="1511" alt="Bildschirmfoto 2022-08-17 um 20 44 05" src="https://user-images.githubusercontent.com/1510/185218308-1a1c20d9-c4eb-4477-8daf-a2dc37c56ba1.png">

**Comment by marianneciara** [comment]
@marcoow Does this happen only after resizing the browser window or does it happen even when the page loads at that screen size? I'm only able to replicate the second screenshot, which I think is linked to the lax.js animation library on that section. I'm not able to replicate the first screenshot at all.

Can you confirm:
- Is it still happening on the [more recent preview link](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/blog/2020/12/15/building-prototypes-with-emberjs-and-ember-hotspots/)?
- Does it only happen after resizing the browser or even on page refresh?
- Which browser and version you're using

Thanks!

**Comment by marcoow** [comment]
It happened without resizing the window but seems to work now 👍
