### ISSUE TITLE
Alignment of open source logos is off

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1847]
The vertical alignment of the open source logos seems to be off a bit, e.g.:

<img width="807" alt="Bildschirmfoto 2022-08-17 um 20 30 38" src="https://user-images.githubusercontent.com/1510/185216112-da1dcbcb-f4bb-4a8c-ae6f-8e379916a8fa.png">

**Comment by marianneciara** [comment]
This is ready for review, [preview link](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/).
