### ISSUE TITLE
Link Ember Europe and EmberFest

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1848]
The Ember Europe and EmberFest logos should link to the respective sites (http://embereurope.org and http://emberfest.eu):

<img width="640" alt="Bildschirmfoto 2022-08-17 um 20 31 48" src="https://user-images.githubusercontent.com/1510/185216341-fdb7fefc-43ad-4e8b-a1b4-5a7fb527e3af.png">

**Comment by marianneciara** [comment]
This is ready for review, [preview link](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/).
