### ISSUE TITLE
Use better background for the Ember Documentary video

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1849]
The background of the Ember documentary video currently shows people that work for a different company:

<img width="1511" alt="Bildschirmfoto 2022-08-17 um 20 33 02" src="https://user-images.githubusercontent.com/1510/185216544-483fca2d-79e4-498f-bfff-ffa4a5a1e119.png">

On the current site we have an auto-playing video – could we use that again?

**Comment by marianneciara** [comment]
This is ready for review, [preview link](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/ember-consulting/). Let me know if you want to provide a higher resolution mp4 file (though I'm mindful of performance as it's already 4.9 MB).
