### ISSUE TITLE
Fix link on ErlEF teaser

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1850]
The link on the ErlEF teaser currently results in a 404 – it should link to http://erlef.org:

<img width="489" alt="Bildschirmfoto 2022-08-17 um 20 34 38" src="https://user-images.githubusercontent.com/1510/185216778-ebfa7a38-b725-4503-9186-f8e732bf18de.png">

**Comment by marianneciara** [comment]
This is ready for review, [preview link](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/expertise/elixir-phoenix/).
