### ISSUE TITLE
EuroRust is duplicated

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1851]
<img width="1511" alt="Bildschirmfoto 2022-08-17 um 20 35 55" src="https://user-images.githubusercontent.com/1510/185216922-ff9b263e-8ec1-4348-b1e5-6e1e8cf6b8d1.png">

**Comment by marianneciara** [comment]
This is ready for review, [preview link](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/events/).
