### ISSUE TITLE
Order talks by descending date

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1852]
The talks should be order by descending date, thus with the latest talk on the top of the page:

<img width="1511" alt="Bildschirmfoto 2022-08-17 um 20 36 39" src="https://user-images.githubusercontent.com/1510/185217105-aa9cf4ea-10bb-42c3-9c4c-93a5fd2c6000.png">

**Comment by marianneciara** [comment]
This is ready for review, [Events page](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/events/) and [Talk page](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/talks/).
