### ISSUE TITLE
Fix category selection on the blog page

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1853]
The blog category selector currently has 2 arrows/chevrons which looks a bit strange – I suggest we keep only 1:

<img width="389" alt="Bildschirmfoto 2022-08-17 um 20 37 53" src="https://user-images.githubusercontent.com/1510/185217397-30d74fe9-bbc9-4965-aa0c-3e9b4c47cd22.png">

Also, I'd use a regular select and only style the currently selected value but use the native UI for the options list.

**Comment by marianneciara** [comment]
This is ready for review, [preview link](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/blog/). 

Note that this adds a new JS dependency as we need JS to go to the selected URL.

**Comment by marcoow** [comment]
> Note that this adds a new JS dependency as we need JS to go to the selected URL.

Not an actual 3rd party dependency though, right? Just a few lines of JS?

**Comment by marianneciara** [comment]
Yes exactly – just a few lines of JS, no actual dependencies. As this UI element won't work without JS I've just added a CSS class so it's hidden when JS isn't enabled.
