### ISSUE TITLE
Dates on the blog articles aren't consistent

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1854]
The dates on the blog articles aren't consistent. E.g. this one shows January 11 on the overview but August on the detail page:

<img width="428" alt="Bildschirmfoto 2022-08-17 um 20 39 53" src="https://user-images.githubusercontent.com/1510/185217693-454812c7-a6e3-4f99-b1e7-d7ee404e5a50.png">

<img width="1511" alt="Bildschirmfoto 2022-08-17 um 20 39 58" src="https://user-images.githubusercontent.com/1510/185217699-d8010697-d023-4f49-a08a-ef4b44249ef9.png">

**Comment by marianneciara** [comment]
This has been fixed, [preview link for this blog post.](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/blog/2022/01/11/this-week-in-os-2/)
