### ISSUE TITLE
Vertically align elements of blog teasers

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1855]
In this example, I think the authors should all be aligned at the bottom of the respective box?

<img width="1358" alt="Bildschirmfoto 2022-08-17 um 20 41 18" src="https://user-images.githubusercontent.com/1510/185217880-93ac2665-d9c3-41ec-ae03-dfff48205a3d.png">

**Comment by marianneciara** [comment]
This is ready for review, [preview link.](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/blog/)
