### ISSUE TITLE
Fix syntax highlighting of blog code snippets

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1856]
The syntax highlighting of the code snippets in the blog seems strange. I'd say let's use what we have currently on simplabs.com which is highlight.js (at build time) with the Github theme.

<img width="1511" alt="Bildschirmfoto 2022-08-17 um 20 42 45" src="https://user-images.githubusercontent.com/1510/185218209-481d847c-a306-40ad-bfce-39a975cf17bd.png">

**Comment by marianneciara** [comment]
@marcoow We're currently using the official 11ty plugin [`@11ty/eleventy-plugin-syntaxhighlight`](https://www.11ty.dev/docs/plugins/syntaxhighlight/) for syntax highlighting. The purple and blue colors in the screenshot were some custom CSS that was added on top of it, which I've now updated so it's a little closer to the current site. [Here's an example article](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/blog/2021/11/09/automating-ember-learning-releases-with-rust/).

Unfortunately the 11ty plugin doesn't mirror how highlight.js transforms the code snippets, and it looks like the highlight.js implementation on the current site is relatively custom ([simplabs.github.io](https://github.com/simplabs/simplabs.github.io)/[lib](https://github.com/simplabs/simplabs.github.io/tree/master/lib)/[markdown-content](https://github.com/simplabs/simplabs.github.io/tree/master/lib/markdown-content)/[htmlize-markdown.js](https://github.com/simplabs/simplabs.github.io/blob/master/lib/markdown-content/htmlize-markdown.js)).

As we've gone over time and I'm not currently available for new scope until 22nd September, do you think the current styling is closer to what you're looking for or can you think of an easier way of doing it?

**Comment by marcoow** [comment]
Yeah, so it's not really important to me that we're using highlight.js specifically but if you look at e.g. [this article](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/blog/2021/11/26/publish-on-npm/), the YAML has essentially no highlighting at all. That seems like a bug since the HTML has a bunch of classes for the different elements:

```<pre class="language-yaml"><code class="language-yaml"><span class="token key atrule">name</span><span class="token punctuation">:</span> Release<br><br><span class="token key atrule">on</span><span class="token punctuation">:</span><br>  <span class="token key atrule">push</span><span class="token punctuation">:</span><br>    <span class="token key atrule">tags</span><span class="token punctuation">:</span><br>      <span class="token punctuation">-</span> <span class="token string">"*"</span><br><br><span class="token key atrule">jobs</span><span class="token punctuation">:</span><br>  <span class="token key atrule">release</span><span class="token punctuation">:</span><br>    <span class="token key atrule">name</span><span class="token punctuation">:</span> Release<br>    <span class="token key atrule">runs-on</span><span class="token punctuation">:</span> ubuntu<span class="token punctuation">-</span>latest<br><br>    <span class="token key atrule">steps</span><span class="token punctuation">:</span><br>      <span class="token punctuation">-</span> <span class="token key atrule">uses</span><span class="token punctuation">:</span> actions/checkout@v2<br>      <span class="token punctuation">-</span> <span class="token key atrule">uses</span><span class="token punctuation">:</span> actions/setup<span class="token punctuation">-</span>node@v2<br>        <span class="token key atrule">with</span><span class="token punctuation">:</span><br>          <span class="token key atrule">node-version</span><span class="token punctuation">:</span> 14.x<br>          <span class="token key atrule">registry-url</span><span class="token punctuation">:</span> <span class="token string">"https://registry.npmjs.org"</span><br><br>      <span class="token punctuation">-</span> <span class="token key atrule">run</span><span class="token punctuation">:</span> npm publish<br>        <span class="token key atrule">env</span><span class="token punctuation">:</span><br>          <span class="token key atrule">NODE_AUTH_TOKEN</span><span class="token punctuation">:</span> $</code></pre>```

but there's no styling for these things? Is there just some CSS missing maybe?

**Comment by marianneciara** [comment]
Yes it looks like we needed to add some CSS for all the possible languages and classnames added by the plugin. I've just gone through all the different languages that feature in the blog and added styling where possible.

There are still some limitations, for example some elements are simply not being picked up and given classes (e.g. CSS values, [screenshot](https://share.getcloudapp.com/BluWLbPK)) or different types of elements are being given the same class (e.g. in Handlebars code the difference between HTML tag and data attribute isn't being picked up, [screenshot](https://share.getcloudapp.com/P8u7v244)).

Let me know if anything looks off or if there's anything I've missed.
