### ISSUE TITLE
Fix edge case of huge viewport

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1857]
When viewing the website fullscreen, some pages have visual inconsistencies:

<img width="2560" alt="Bildschirmfoto 2022-08-17 um 20 45 28" src="https://user-images.githubusercontent.com/1510/185218924-fcacc801-b0b7-4fed-a45e-b5c68e8a516d.png">
<img width="2560" alt="Bildschirmfoto 2022-08-17 um 20 47 07" src="https://user-images.githubusercontent.com/1510/185218953-0f38c5fb-e077-4d89-a077-33fb47c336a3.png">
<img width="2560" alt="Bildschirmfoto 2022-08-17 um 20 47 30" src="https://user-images.githubusercontent.com/1510/185218977-9ec4e62c-7adb-4022-8439-c69f4dcd8eb5.png">

**Comment by marianneciara** [comment]
This has been fixed, [preview link here](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/).
