### ISSUE TITLE
Logo carousel on Ember page misses padding on mobile

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1858]
All the logos are crammed together:

<img width="482" alt="Bildschirmfoto 2022-08-17 um 20 52 14" src="https://user-images.githubusercontent.com/1510/185219825-05bb71b0-6ae2-475f-a447-ddf500941f6a.png">

**Comment by marianneciara** [comment]
This has been fixed, [preview link here](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/ember-consulting/).
