### ISSUE TITLE
Some pages scroll horizontally on mobile

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#1859]
Not the most important page but it scrolls slightly horizontally on mobile :)

<img width="454" alt="Bildschirmfoto 2022-08-17 um 20 54 34" src="https://user-images.githubusercontent.com/1510/185220215-817600d8-b581-412e-80e4-c53b70646518.png">

The team augmentation page does as well though (and I assume some others will as well)…

<img width="504" alt="Bildschirmfoto 2022-08-17 um 20 58 12" src="https://user-images.githubusercontent.com/1510/185220807-4f02758c-ee4a-4c56-8982-36341aa67a59.png">

**Comment by marianneciara** [comment]
This has been fixed! Added some CSS for word-breaks and auto hyphens. [Preview link.](https://deploy-preview-1--mainmatter-11ty-redesign.netlify.app/)
