### ISSUE TITLE
Add tech page on Rails

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#188]
This is a follow-up to #176 - we shouldn't block the facelift until this is done

**Comment by oliverbarnes** [comment]
Here's a first stab:

Ruby on Rails
The ubiquitous reference in backend frameworks

Ruby on Rails revolutionized web development back in the day, elegantly implementing concepts taken for granted now, such as convention over configuration, don't repeat yourself (DRY) and REST, making them ubiquitous. Rails is the benchmark all backend frameworks are measured against, and Ruby the benchmark for expressive, friendly programming language with a low-bar for adoption by new programmers.

Both enabled rapid-development of products for many startups over the years, and continue to do so in a field crowded with competitors, even as the paradigm has shifted from monolithic web MVC apps to more fragmented services and multiple front-ends with their own, dedicated web frameworks. Rails continues to be a solid choice for quickly building an API or internal backend service within a micro-services architecture.

It is also now present in long-living legacy code-bases, rubbing shoulders with other venerable technologies like Java in the legacy space, and is likely to stick around for a long time.

simplabs has had constant demand for Rails work from clients over the years, and we're happy to meet it. Together the team has decades of Rails experience, is comfortable working with monoliths and services, codebases old or new, and of course, integrating with Ember and other front-end technologies.
