### ISSUE TITLE
Overlay animation and text overlay to improve

### ISSUE THREAD

**Issue by davidhajba** [mainmatter/mainmatter.com#1889]
hey, we agreed with Marco the following overlay animation and text overlay details could be improved
check the overview [HERE](https://www.loom.com/share/bf3b0258b770421c86865225a07bddaf)

**Comment by beerinho** [comment]
Just to add to this, I noticed that it does work on the homepage, but as @davidhajba mentions on another page, it just starts too late

**Comment by lolmaus** [comment]
I find the current design of the text overlay frustrating:
* I'm unable to read the intended title.
* When I start scrolling, my attention is at the revealed portion of the page, not the disappearing part.
* My mouse wheel is configured to scroll three lines per tick, without animation. A single tick of the wheel instantly removes the teal rectangle from the viewport, so I don't see any animation. I had to slowly scroll by dragging the scrollbar to see the animation.
* My viewport width is 1200px sans the classic scrollbar.

<details>
  <summary>Animated screenshot</summary>
  
  ![simplabs scrolling](https://user-images.githubusercontent.com/200884/193626612-f22670dd-6ede-4c43-bcc3-e2de1210fdd4.gif)
  
</details>

**Comment by lolmaus** [comment]
On ultrawide (3840x1440 sans bars), the hidden word gets revealed at the very last moment of scrolling, without animation, so there's no way I would've noticed it.

Also there's a glitch with the purple overlay not fully covering the hero image.

<details>
  <summary>Animated screenshot</summary>
  
  
![simplabs scrolling 2](https://user-images.githubusercontent.com/200884/193626947-cf280c5a-ff39-4299-8859-d6bfe6746dac.gif)

  
</details>
