### ISSUE TITLE
Upcoming events section

### ISSUE THREAD

**Issue by SaeLLo** [mainmatter/mainmatter.com#1922]
Would it make sense to add something like "no events planned at the moment" when there are none (which is never really the case I guess - We have the dates for EuroRust 2023) already? Otherwise, it looks like an error. 

Additionally, we can add a section with past events or at least link to Emberfest and Eurorust page.

**Comment by marcoow** [comment]
yes, definitely – we should add sth. like that (or just remove the "upcoming events" header)
