### ISSUE TITLE
Add meta tags for Twitter's large summary card

### ISSUE THREAD

**Issue by emmasofiah2o** [mainmatter/mainmatter.com#1961]
Our link previews on Twitter currently don't show the entire og:image. 

**Current state:**
<img width="592" alt="Screenshot 2022-12-09 at 15 07 31" src="https://user-images.githubusercontent.com/83696750/206720288-7d9547f0-5730-486f-be3f-5dc64f201c22.png">
**Desired state:**
<img width="571" alt="Screenshot 2022-12-09 at 15 08 15" src="https://user-images.githubusercontent.com/83696750/206720402-6f0338a9-b385-4d25-98ee-e1fc244174ed.png">

I have researched and Twitter suggests implementing the following meta tags to add a large image to link previews. 
[Source code](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image) (see sample code).

**Comment by marcoow** [comment]
done via #1964
