### ISSUE TITLE
Modify blog section to display images better

### ISSUE THREAD

**Issue by emmasofiah2o** [mainmatter/mainmatter.com#1991]
@davidhajba realized we need to change a few things on the website to optimize the way blog post images are displayed. He suggested we
1) remove the black overlay from the small images in the cards list
2) change the mobile version to display the title the same way as the desktop version (below the image).

Here is the visual representation of what we would like the updated blog section to look like
Desktop version:

![blog main - pattern](https://user-images.githubusercontent.com/83696750/217206279-76849eba-aacc-4bea-aa25-d1f098fa14be.png)

Mobile version:

![Blog main Copy](https://user-images.githubusercontent.com/83696750/217206494-eb850c1d-9519-49db-82ae-e6fb3b938128.png)

**Comment by yaigrie** [comment]
I will close this issue, as the blog thumbnails will change with the upcoming design update :)
