### ISSUE TITLE
https://rust-web-services-workshop.mainmatter.com/

### ISSUE THREAD

**Issue by SaeLLo** [mainmatter/mainmatter.com#2044]
The "For Who?" information is in there twice (as commented before). I recommend deleting this "This workshop is intended for developers who have some experience with Rust and want to learn more about its problem domain for web applications. It is not necessary to have written Rust in a production environment yet. If you are just starting out with Rust, we will provide you with preparatory material beforehand." from the "Mode" section.

**Comment by marcoow** [comment]
argh, I think I misunderstood the comment the first time…
