### ISSUE TITLE
Create new page for startups and scale-ups

### ISSUE THREAD

**Issue by oscard0m** [mainmatter/mainmatter.com#2047]
# Description
This task aims to add a new page for mainmatter.com.

## Resources
- 📓 [Notion Task + discussion](https://www.notion.so/mainmatter/Web-Start-Up-b5114dc7a8884a26b9b5fb0daa501175?pvs=4)
- 🎨 [Sketch Design](https://www.sketch.com/s/9d642daa-3698-4c49-b32b-14feec941f8e)

# Work
Here's a mapping of how the section structure is going to change in the following way:
| Before | After |
|--------|--------|
| `hero` ![image](https://github.com/mainmatter/mainmatter.com/assets/2574275/773e5892-97ed-47ef-a443-af9f940553bd) | `hero` <img width="652" alt="image" src="https://github.com/mainmatter/mainmatter.com/assets/2574275/3890ad7e-ea16-4b46-aadc-837bf0d46309"> |
| `our services` ![image](https://github.com/mainmatter/mainmatter.com/assets/2574275/48ee4331-ef53-4d03-aa70-c316be7af7b5) | `our services` <img width="524" alt="image" src="https://github.com/mainmatter/mainmatter.com/assets/2574275/9df08b35-5d2e-4bc2-8b9e-e666a3ed7b28"> |
| `logo list`![image](https://github.com/mainmatter/mainmatter.com/assets/2574275/8fbea643-cc3b-4b42-99bb-cfffc5c34be8) | `call to action` <img width="650" alt="image" src="https://github.com/mainmatter/mainmatter.com/assets/2574275/6c23c377-e4ed-491a-84c3-0cc9d0fa2317"> |
| `our work` ![image](https://github.com/mainmatter/mainmatter.com/assets/2574275/dd04022a-286b-47fd-b390-7196014f9f04) | `logo list` <img width="646" alt="image" src="https://github.com/mainmatter/mainmatter.com/assets/2574275/0da1f365-6a6e-4b6c-b6f9-bbf8e7c6b2e2"> |
| `why mainmatter` <img width="620" alt="image" src="https://github.com/mainmatter/mainmatter.com/assets/2574275/ba27a70b-08cf-4b86-8aeb-8848bf6aa54a"> | `why mainmatter` <img width="294" alt="image" src="https://github.com/mainmatter/mainmatter.com/assets/2574275/9038a163-83f8-4d49-ab93-185dcda1049e"> | 
| `call to action` ![image](https://github.com/mainmatter/mainmatter.com/assets/2574275/6e55d2a2-c483-4128-ae9d-60c8a5b47d9c) | `contact us` <img width="630" alt="image" src="https://github.com/mainmatter/mainmatter.com/assets/2574275/b27c4e85-df1c-49f9-b1fc-dab4fe468716"> |
| `contact us` ![image](https://github.com/mainmatter/mainmatter.com/assets/2574275/2b8849ec-2a4b-4a37-9e6c-379f32b9212b) | `our work` <img width="620" alt="image" src="https://github.com/mainmatter/mainmatter.com/assets/2574275/ba27a70b-08cf-4b86-8aeb-8848bf6aa54a"> |
| `footer`![image](https://github.com/mainmatter/mainmatter.com/assets/2574275/f6e373bd-19e8-40df-a3d4-c974ade20821) | `footer` <img width="624" alt="image" src="https://github.com/mainmatter/mainmatter.com/assets/2574275/63e2f518-5566-49dd-96a7-b5b8db9b8466"> |

Once we've validated if my understanding of how the sections of the homepage are changing I will write down a detailed TODO of how each of the sections is changing.

**Comment by oscard0m** [comment]
@marcoow @SaeLLo @marcoow Could you validate if my understanding of how the sections are mapped is correct? @inesilva 

Also, it would be good to give a name to each section so we all speak the "same language" and can refer to it in Notion, Sketch, Slack, etc.

**Comment by marcoow** [comment]
This isn't about changing the existing root page – we're building a **new** page

**Comment by oscard0m** [comment]
> This isn't about changing the existing root page – we're building a **new** page

Does this mean this page will be under `/startup` or something like that?

**Comment by inesoaresilva** [comment]
Where will this page be placed?

**Comment by marcoow** [comment]
Something like `/startups`, yes – we can decide on the exact path later. The page won't show up in the navigation or anything

**Comment by marcoow** [comment]
done
