### ISSUE TITLE
`yarn install` fails in local environment because of `gravityci/cli` `devDependency` is private

### ISSUE THREAD

**Issue by oscard0m** [mainmatter/mainmatter.com#2048]
# Description
`@gravityci/cli` is causing `yarn install` errors in local environment because it is a private package.

We need a solution where this friction is removed for our developers but still run `@gravityci/cli` in our pipeline.

# Context
This is creating friction in local environment when somebody wants to create a blog post in mainmatter:
* https://mainmatter.slack.com/archives/C02BFVBD6A1/p1679664722557699
* https://mainmatter.slack.com/archives/C02BFVBD6A1/p1683903795699229

**Comment by oscard0m** [comment]
The password shared in 1Password link apparently expired. In a quick research in Mainmatter's 1Password I did not find the token/credentials.  

Still, this solution implies each developer and **non-developer** will have the same issue for a package we plan to make public sooner than later. Also, I'm not sure if the token privileges we are sharing has the right permissions/limits.

@marcoow is it ok if we remove the friction this is creating for developers in the local environment by:
- Removing `@gravityci/cli` as `devDependency` in `package.json`
- Install `@gravityci/cli` as `devDependency` in our GitHub Workflow immediately after installing all dependencies.

Of course, I think we should review the code of the `@gravityci/cli` package and make the package public [as Chris suggested](https://mainmatter.slack.com/archives/C02BFVBD6A1/p1679667351955529).

**Comment by marcoow** [comment]
> Removing @gravityci/cli as devDependency in package.json
> Install @gravityci/cli as devDependency in our GitHub Workflow immediately after installing all dependencies.

sure. that works 👍
