### ISSUE TITLE
Add "Online" to the Rust Web-services Workshop page

### ISSUE THREAD

**Issue by SaeLLo** [mainmatter/mainmatter.com#2050]
-> https://rust-web-services-workshop.mainmatter.com/

- We should put "online" next to the date in the hero section.
- Additionally, adding this information to the "Mode section" makes sense: "The workshop will be held over three afternoons and online. Each session will include practical examples, and in addition, we will provide optional homework for you to work on."

**Comment by oscard0m** [comment]
Hey @SaeLLo,

Thanks for opening this. 

### Update the hero section
I need clarification on what is **the hero** section. 

- Would it be the page [`/workshops/workshops/introduction-to-rust-for-web-developers`](https://deploy-preview-325--eurorust.netlify.app//workshops/introduction-to-rust-for-web-developers)? 

- Your request would be adding a kind of <kbd>ONLINE</kbd> next to the Date?
<img width="500" alt="image" src="https://github.com/mainmatter/eurorust.eu/assets/2574275/f179253a-9fd7-4fb7-afb9-e0959944f833">

### Mode section
I need clarification on what is the **mode** section. 

- Is it the [`/workshops`](https://deploy-preview-325--eurorust.netlify.app//workshops/) page?

- Your request would be to add a second paragraph to the **Introduction to Rust for Web Developers** Workshop, is that correct?

`The workshop will be held over three afternoons and online. Each session will include practical examples, and in addition, we will provide optional homework for you to work on."`

<img width="500" alt="image" src="https://github.com/mainmatter/eurorust.eu/assets/2574275/026a483a-21df-4913-a0e7-aa85ba6ef47e">

**Comment by SaeLLo** [comment]
@oscard0m We need the changes here: https://rust-web-services-workshop.mainmatter.com/
not at the EuroRust page.

**Comment by oscard0m** [comment]
Sorry for the confusion, I will transfer the issue to `mainmatter.com` repo 👍🏽

**Comment by SaeLLo** [comment]
Sorry, I think I out it in the EuroRust project section...

**Comment by oscard0m** [comment]
@inesilva will take care of this. I think @davidhajba should be involved in updating the designs

**Comment by inesoaresilva** [comment]
What about using the word 'Remote' as we have in other places, e.g - https://mainmatter.com/services/workshops/design-system-kickoff-interface-inventory/ ? 
<img width="1103" alt="image" src="https://github.com/mainmatter/mainmatter.com/assets/15367376/8c0083f4-3011-4c0c-be08-fd4078d8d61b">
@davidhajba

**Comment by davidhajba** [comment]
please let me know how can I help here.

**Comment by inesoaresilva** [comment]
> please let me know how can I help here.

It was to get your opinion on what text (online vs remote) to put and where to place it, e.g, in front of the text or below, but I guess it is a minor detail.
i'll move forward like above ☝️  and let me know if there is anything that should change

**Comment by davidhajba** [comment]
hey @inesilva 
if you add 'Remote' I would not add it in a new row, I would suggest:

11.-13. (14:00 - 18:00 CEST) July 2023 - Remote
