### ISSUE TITLE
Create landing page for Rust telemetry workshop

### ISSUE THREAD

**Issue by LukeMathWalker** [mainmatter/mainmatter.com#2171]
We want to offer [this workshop](https://mainmatter.com/services/workshops/telemetry-for-rust-apis/) again in December, as an online event that folks can sign up for.

We need a landing page for it which includes the datetime information as well as a button to book a seat (which will be handled via ti.to cc @marcoow).

Happy to help with the content/any clarification required!

**Comment by marcoow** [comment]
@yaigrie this is the ti.to page: https://ti.to/mainmatter/telemetry-rust-2023/test/bzqctwfgpfedorgd

**Comment by yaigrie** [comment]
@LukeMathWalker I think this is going to have the same layout as the Svelte & SvelteKit Workshop https://mainmatter.com/svelte-sveltekit-workshop/ :)
Do you have any nice photos of yourself giving a workshop that I could use?

**Comment by LukeMathWalker** [comment]
I should have a picture from the one we ran at EuroRust, let me search for it!

I think we should also weave into the landing page some of the good feedback we got there—e.g.

> I usually avoid workshops. The pace of more than 3 people is hard to sync: I always feel rushed in some bits, slowed down in others. You fixed that with the code-centric approach, I really enjoyed that [...] and I was able to fully use the time and knowledge of the trainer!
