### ISSUE TITLE
Newsletter signup

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#2188]
We should build a component that allows people to sign up for a newsletter. This could be useful in a number of places, e.g.

* the general workshop pages under https://mainmatter.com/services/workshops/ where we could say "get notified on future dates of this workshop" or so
* on the events page maybe where we can say "get notified of future events"
* maybe on the blog
* etc.

I'd like to have a reusable a component as a first step, a bit similar to what we have at the bottom of most pages currently (_"Grow your business with us"_)

**Comment by yaigrie** [comment]
if we go for the plain background version for the cta, we could continue doing that here

![Group 4 2](https://github.com/mainmatter/mainmatter.com/assets/39055470/22c453f4-b861-4898-8319-a652cbdf3c71)

**Comment by marcoow** [comment]
Yes, I think sth. like this would work - let's explore and finalize in Sketch?

**Comment by marcoow** [comment]
this is done
