### ISSUE TITLE
Make call to action in the footer more prominent

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#2198]
The call to action link in the footer isn't super prominent:

![Bildschirmfoto 2023-11-09 um 16 12 13](https://github.com/mainmatter/mainmatter.com/assets/1510/b09297e9-dad1-4e66-beaa-f361d1a644d5)

It's only a small text link – we should design a solution the stands out much more

**Comment by yaigrie** [comment]
At the very least we could use the bigger button size, maybe also include the arrow
But maybe it could also be beneficial to remove the background image to reduce visual distraction?


![Group 4](https://github.com/mainmatter/mainmatter.com/assets/39055470/7cf86565-52a6-473b-9fe1-30c6c4dc7e6b)

**Comment by marcoow** [comment]
I'd say let's explore some designs in Sketch?

**Comment by yaigrie** [comment]
@marcoow I started with a few designs in sketch: https://www.sketch.com/s/7baa7317-7ec9-48b5-9584-4edb6163c143
