### ISSUE TITLE
Add dedicated image to Rust adoption blog post

### ISSUE THREAD

**Issue by LukeMathWalker** [mainmatter/mainmatter.com#2258]
It'd be nice to have a dedicated image for #2257 rather than re-using an existing one.
Is that something you have time to help me with @yaigrie?

**Comment by yaigrie** [comment]
@LukeMathWalker Sure, what do you have in mind? :)

**Comment by LukeMathWalker** [comment]
Nothing specific, but in terms of vibes it's meant to be somewhat of a guide/roadmap, very checklist-y. I don't know if that helps 😅
