### ISSUE TITLE
Content is hidden on smaller resolutions

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#227]
Unless there's a reason to hide content I think we should make it visible at all resolutions.

![image](https://user-images.githubusercontent.com/845767/47918208-20277c80-deac-11e8-898f-a6ec0141b13f.png)
![image](https://user-images.githubusercontent.com/845767/47918214-26b5f400-deac-11e8-86c5-78496570e25a.png)

**Comment by wadie** [comment]
I believe it's better to have less content on smaller resolutions, to keep it light and simple.

@marcoow What do you think ?

**Comment by ghislaineguerin** [comment]
@wadie Ideally we assume all the content we have on our website has an influence on the users decision making process. If we’d consider one piece of content creating noise or bloating the page, then we apply the same criteria for any resolution. Once we start tracking conversion rates and metrics we’ll assume every user has been exposed to the same information. Does that make sense? In any case where order of content matters, we’ll use flex order properties to maximize visibility on mobile.

**Comment by marcoow** [comment]
I think the reason why the content was originally removed on mobile was that it just didn't look right in the smaller box - of course the real problem that needs to be fixed is just that, that it didn't look right. So I agree, we should use the same content regardless of the resolution or if the content is not important/valuable for anyone, remove it for **all** resolutions.
