### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#23]
…following this guide: https://jekyllrb.com/docs/continuous-integration/

**Comment by ganeshbsub** [comment]
List of outdated external links:
- [x] - blog/2013/06/15/authentication-in-emberjs.html : https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/rest_adapter.js
- [x] - blog/2013/08/08/better-authentication-in-emberjs.html : there are some comments referenced here which don't exist anymore.
- [x] - blog/2014/01/20/embersimpleauth-010.html : https://github.com/simplabs/ember-simple-auth/tree/master/examples

**Comment by marcoow** [comment]
> - blog/2013/06/15/authentication-in-emberjs.html : https://github.com/emberjs/data/blob/master/packages/ember-data/lib/adapters/rest_adapter.js

https://github.com/emberjs/data/blob/master/addon/adapters/rest.js

> - blog/2013/08/08/better-authentication-in-emberjs.html : there are some comments referenced here which don't exist anymore.

remove links

> - blog/2014/01/20/embersimpleauth-010.html : https://github.com/simplabs/ember-simple-auth/tree/master/examples

remove links

**Comment by ganeshbsub** [comment]
Next set of links: **(I think ember-cli-deploy has its own website now. I can update those links. Just listing here for reference)**
- [ ] - blog/2014/06/30/using-ember-simple-auth-with-ember-cli.html : http://ember-simple-auth.simplabs.com/ember-simple-auth-api-docs.html , http://ember-simple-auth.simplabs.com/ember-simple-auth-oauth2-api-docs.html , https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth-oauth2
- [ ] - blog/2014/07/25/testing-with-ember-simple-auth-and-ember-cli.html : http://ember-simple-auth.simplabs.com/ember-simple-auth-api-docs.html#SimpleAuth-Stores-Ephemeral
- [ ] - blog/2015/07/29/ember-simple-auth-10-a-first-look.html : https://github.com/simplabs/ember-simple-auth/compare/jj-abrams
- [x] - blog/2015/12/03/ember-cli-deploy-notifications.html : http://ember-cli.com/ember-cli-deploy/docs/v0.5.x/deployment-context/
- [ ] - clients/index.html : http://shuddle.us/
- [x] - blog/2015/12/03/ember-cli-deploy-notifications.html: http://ember-cli.com/ember-cli-deploy/docs/v0.5.x/pipeline-hooks/ ; https://t.co/6yhjmjQrYD -> This is just the ember-cli-deploy website

Also, @marcoow shall I just remove the old_website directory? Not sure why it's still there.

**Comment by marcoow** [comment]
> Also, @marcoow shall I just remove the old_website directory? Not sure why it's still there.

where is that? don't see it on github

**Comment by marcoow** [comment]
> http://ember-simple-auth.simplabs.com/ember-simple-auth-api-docs.html

http://ember-simple-auth.com/api/

> http://ember-simple-auth.simplabs.com/ember-simple-auth-oauth2-api-docs.html

http://ember-simple-auth.com/api/

> https://github.com/simplabs/ember-simple-auth/tree/master/packages/ember-simple-auth-oauth2

https://github.com/simplabs/ember-simple-auth/blob/master/addon/authenticators/oauth2-password-grant.js

**Comment by marcoow** [comment]
> http://ember-simple-auth.simplabs.com/ember-simple-auth-api-docs.html#SimpleAuth-Stores-Ephemeral

http://ember-simple-auth.com/api/classes/EphemeralStore.html

**Comment by marcoow** [comment]
>  https://github.com/simplabs/ember-simple-auth/compare/jj-abrams

remove link

> http://ember-cli.com/ember-cli-deploy/docs/v0.5.x/deployment-context/

http://ember-cli-deploy.com/docs/v0.6.x/deployment-context/

> http://shuddle.us

remove link

>  http://ember-cli.com/ember-cli-deploy/docs/v0.5.x/pipeline-hooks/ 

http://ember-cli-deploy.com/docs/v0.6.x/pipeline-hooks/

> https://t.co/6yhjmjQrYD

http://ember-cli-deploy.com

**Comment by marcoow** [comment]
@ganeshbsub: I think we should switch on `check_html` in html-proofer that doesn't seem to be enabled by default (see https://github.com/gjtorikian/html-proofer#configuration).
