### ISSUE TITLE
Blog posts are missing the category

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#231]
For SEO reasons we want to have the category show on every blog post.
The expected behavior is that the user clicks on it and can browse an archive of blog post related to the category.

**Comment by wadie** [comment]
Totally agreed - I just wasn't sure which tags we could have.

I've already added some `elixir` and `ember` tags.

**Comment by ghislaineguerin** [comment]
@wadie I think we also want users to be able to navigate to the blog category from within a post. 
Do we currently have a filtered list view for each tag?

**Comment by marcoow** [comment]
@ghislaineguerin: we don't have these category pages and while I agree we should eventually have them, I don't think we necessarily need them for the initial release?

**Comment by marcoow** [comment]
I added the missing categories in b36b2127642f7d228f018cec626a0dc7963628a0 btw - see my comment here: https://github.com/simplabs/simplabs.github.io/pull/219#issuecomment-441285403

**Comment by ghislaineguerin** [comment]
@marcoow I saw that, thanks. I meant showing the categories on the blog posts as well, at some point we want users to link from there and discover our content pillars. 
Agree that we can launch the website without including that.

**Comment by marcoow** [comment]
this will be fixed as part of the new website
