### ISSUE TITLE
Content Strategy Update - Homepage

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#232]
### What's the problem?
Current content on the homepage needs to be updated so that we can increase our SEO rank and reflect our key service advantages (the simplabs advantage). 

With a focus on the most frequent concerns expressed by people when considering to hire software development services, where they are looking to minimize risk and increase the odds of launching a successful, built to last, solution.

### What is the simplabs advantage?
Team Expertise + Built to last

### Updated Content

> **Leveraging Trainline's full market potential**
> 
> Trainline hired us to build out a mobile web app to serve as a companion to their existing desktop app. We worked with Trainline to deliver a **progressive, scalable, high-performing** application along with an **improved engineer process,** enabling them to accomplish their business goals **for years to come**. 
> 

> **Laying out a solid foundation for Timify**
> 
> When Timify decided it was time to re-engineer their existing product, they trusted us to **bring them into the future**. We added engineering capacity to their team and helped to **build a solid foundation** that would enable Timify to iterate fast and **launch on-schedule** without sacrificing quality.

Mockup
![homepage-draft](https://user-images.githubusercontent.com/845767/47997614-b94cd200-e0fc-11e8-9ff4-f641cdf49f6c.jpg)

**Comment by ghislaineguerin** [comment]
@marcoow This is my first proposed change to make our value proposition more visible to visitors. Take a look and let me know your thoughts. My plan is to first define these updates for all pages and then implement all at once.

**Comment by marcoow** [comment]
I like it!

I'd change the wording very slightly though:

Leveraging Trainline's full market potential

Trainline hired us to build out a mobile web app to serve as a companion to their existing desktop app. We worked with their team to deliver a scalable, high-performance application along with establishing an improved engineering process, enabling them to accomplish their business goals for years to come.

Laying out a solid foundation for Timify

When Timify decided it was time to re-engineer their existing product, they trusted us to bring them into the future. We added engineering capacity as well as advanced expertise to their team and helped to build a solid foundation that would enable Timify to iterate fast and launch on-schedule without sacrificing quality.

**Comment by marcoow** [comment]
I think we should always pass these things by our native speakers @geekygrappler, @mansona and @oliverbarnes to make sure we're not making stupid mistakes :)

**Comment by ghislaineguerin** [comment]
@marcoow agree. Do you think it's best for them to review for each page as I go adding more? or wait until all is ready?

**Comment by geekygrappler** [comment]
I think we should review once everything is ready. I read over @marcoow comment above and the wording is 👌.

**Comment by marcoow** [comment]
Yes, I'd also say we should do one final pass over all of the text before we release.

**Comment by oliverbarnes** [comment]
I think submitting each page would make reviewing easier actually, and better if done over pull requests (if @ghislaineguerin is already familiar with git/github), so we can clearly see changes. And @marcoow, when suggesting changes to the changes, would be good to highlight what's changed as well.

The english is 👌 for both versions here, and I like the content. I'd just loose the `establishing` from the second version, it was clear before imo

**Comment by ghislaineguerin** [comment]
@marcoow I will be closing this issue and adding this to the content branch
