### ISSUE TITLE
Page titles are below 30 characters

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#234]
Page titles should follow the following format:

Primary Keyword - Secondary Keyword | Brand Name
So in the case of : Work | simplabs
We could have: Full-Service Engineering - Our Work | simplabs  or  Web & Mobile - Our Work | simplabs (these are just examples, we should check with Mark)

Contact Us | simplabs
Imprint | simplabs
Trainline | simplabs
Elixir | simplabs
DD-WRT | simplabs
Expedition | simplabs
About | simplabs
Services | simplabs
Team Augmentation | simplabs
Imprint | simplabs
Work | simplabs
Training | simplabs
Timify | simplabs
Ember | simplabs
Blog | simplabs
Enginification | simplabs
From SPA to PWA | simplabs
Ember.SimpleAuth | simplabs
excellent 2.0.0 | simplabs
Rails API Auth | simplabs
excellent 1.7.2 | simplabs

**Comment by pichfl** [comment]
Given that good titles are 50-70 characters long, here are some examples:

```diff
- Contact | simplabs
+ Contact us for successful projects and increased team effectiveness | simplabs

- Imprint | simplabs
# dropped from Index

- Trainline Case Study | Work | simplabs
+ Mobile web app with Ember.js for Trainline | Work | simplabs

- DD-WRT NXT Case Study | Work | simplabs
+ Providing powerful UI for DD-WRT NXT using Ember.js | Work | simplabs

- Timify Case Study | Work | simplabs
+ Rebuilt MVP for long term success for Timify | Work | simplabs

- Expedition Case Study | Work | simplabs
+ Full-stack work for Expedition online travel magazine | Work | simplabs

- Why simplabs | simplabs
+ Ember.js consulting, Full service solutions | Why us | simplabs

- Services | simplabs
+ Full-stack & tutoring & team augmentation | Our services | simplabs 

- Team Augmentation | services | simplabs
+ Your team, more effective | Team Augmentation | Services | simplabs

- Work | simplabs
+ Successful projects for international clients | Work | simplabs

- Tutoring | simplabs
+ Level up your team's effectiveness with our tutoring | simplabs

- Blog | simplabs
+ Regular tech insights and updates from our team | Blog | simplabs
```

I excluded the titles that were created by blog posts as they were changed to something more fitting already (following the schema `Blogpost title | Blog | simplabs`)

@simplabs/website can someone check my grammar or if the above make sense at all?

**Comment by ghislaineguerin** [comment]
@pichfl I think these look good. You've got some inconsistent use of the - in some places (full stack vs. full-stack). 
I think we should come up with a consistent pattern, so for example, I like how you added "using ember.js" to the dd-wrt case study, but then we aren't consistent with the other case studies, so just wondering if we need to follow some sort of template.

**Comment by pichfl** [comment]
Inconsistencies in wording were somewhat intentional to get in as many possible searches I can, but you're right, we should focus a bit more. Updated my comment to always use `full-stack`
