### ISSUE TITLE
Fix height and padding of hero section

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#2369]
I noticed we're using a fixed, relatively large top padding of 33% on the main hero sections which results in unnecessary space and the actual content to be pushed outside of the viewport:

![Bildschirmfoto 2024-04-21 um 16 45 57](https://github.com/mainmatter/mainmatter.com/assets/1510/c678017d-ecb7-43a6-baad-eaf5d5f22c77)

I think what we really want is:

* the main hero section should have a `min-height` of `100vh` but should grow larger with the content if necessary
* the content in the main hero section should have a minimum padding/margin towards the top to ensure it's offset from the main navigation by a minimum distance

I'd recommend looking at the previous CSS – all of this was present before the energy update I think. It's actually fine on the [homepage](https://mainmatter.com).

**Comment by yaigrie** [comment]
@marcoow This already works when the viewport is large enough
I will lower the breakpoint for this :) 

((The old CSS cut content off if it was larger than the 100vh, so I don't think we want to continue using that))
