### ISSUE TITLE
Add styling for `<code>` elements on workshop pages

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#2404]
e.g. on this page:

![Bildschirmfoto 2024-05-10 um 18 05 03](https://github.com/mainmatter/mainmatter.com/assets/1510/e1f72b6d-8024-40dd-966a-98755d7b51de)

Box, Arc, Rc, Option, etc. are all `<code>` elements and should be styled as code.

**Comment by nchan0154** [comment]
Resolved in #2457
