### ISSUE TITLE
Fix formatting in blog posts

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#2455]
- [ ] `<code>` tags aren't styled
- [ ] italic text isn't styled
- [ ] bold text isn't styled
- [ ] lists aren't styles
- [ ] footnotes don't work
- [ ] strikethrough doesn't work

**Comment by nchan0154** [comment]
I'm looking into this now!

- Can you provide a font file for Core Sans A in Italics? If not, are you ok with faux italics?
- Strikethrough does work for me with double tildes and no extra whitespace `~~Like this~~`, can you confirm or let me know what you're using to do strikethrough? 
@marcoow

**Comment by marcoow** [comment]
I don't know what faux italics are :) but here are the font files: https://drive.google.com/drive/folders/1D5vzHnitozgE4-JezYWVRnwrlkWJ0UxT?usp=sharing

My bad with the strikethrough 🤦
