### ISSUE TITLE
Landing page for the travel industry

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#2459]
We want to add a new landing page targeted at the travel industry. Generally this will have a similar structure/design like https://mainmatter.com/startups/. Here's the structure/content (all text is wip but can be used to build the page with for now):

* Header
  * for the hero image, we should use something related to travel, ideally something that's a bit fun/engaging and not super serious
  * headline "We modernize the travel industry"
  * header text: "We transform travel companies holistically, building modern organizations along with industry-leading products."
* Intro paragraph below the header
  * Mainmatter understands the offerings and operations of the leading players in the travel industry - in fact, we’ve been involved with shaping them. We can transform your company to match these standards. We will assess the status quo, create a roadmap towards your future shape, and guide you throughout the journey.
* Text section with header (similar to "Create a strategic foundation" on https://mainmatter.com/services/launch-your-idea/):
  * headline "Overcoming challenges together"
  * text

> The travel industry is under rising pressure as user expectations grow, entry barriers decrease, and disruptive newcomers enter the market. To maintain or expand their market share, companies must innovate quickly, deliver impressive results, and adapt flexibly to a changing landscape.
> 
> Mainmatter focuses on holistic transformations of companies to enhance their capabilities and offerings. Our expertise comes from partnering with industry leaders like Trainline and Rail Europe, and from our experience with top tech companies in other sectors such as Qonto and Aleph Alpha. Our collaboration with client teams allows us to impart our knowledge, build internal expertise, and enhance organizations, processes, and culture.
* "We'll work with you to:" (like on e.g. https://mainmatter.com/services/launch-your-idea/):
  * "Assess the status quo via a thorough analysis of code, architecture, infrastructure, and processes, as well as interviews with stakeholders."
  * "Prepare a roadmap for transforming the product as well as the development organization behind it."
  * "Guide your team through the transformation phase."
* Section with case studies:
  * large case study: RailEurope (like on https://mainmatter.com/services/strategic-advice/)
  * quote Jürgen Witte (like on https://mainmatter.com/services/strategic-advice/)
  * large case study: Trainline
  * 3 small case studies below (like on https://mainmatter.com): HopSkipDrive, Terminal49, Aleph Alpha
* 3 blog posts (like on the bottom of https://mainmatter.com/rust-consulting/)
* discover our other services (like on the bottom of https://mainmatter.com/services/team-reinforcement/)
* newsletter signup (like on the bottom of https://mainmatter.com)
* "grow your business with us" (like on the bottom of https://mainmatter.com)

**Comment by marcoow** [comment]
@nchan0154 this is the new landing page I had mentioned – is this enough guidance for you to get started with this?

**Comment by nchan0154** [comment]
Yep, should be enough to get started with.

**Comment by marcoow** [comment]
done
