### ISSUE TITLE
Blog list accessibility issues 

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#250]
There are some accessibility issues that must be solved on the blog listing page:

- [ ] - The hyperlink must provide a descriptive aria-label that includes the blog post title.
- [ ] - The blog post summary must be hidden from screen readers.
- [ ] - The title of the blog post must be inside a heading tag.
- [ ] - Screen readers can't read the post category, date or author.

**Comment by ghislaineguerin** [comment]
What's the problem?
- The hyperlink must provide a descriptive aria-label that includes the blog post title.
- The blog post summary must be hidden from screen readers.
- The title of the blog post must be inside a heading tag.
- Screen readers can't read the post category, date or author.

**Comment by pichfl** [comment]
This issue is no longer valid for the new layout
