### ISSUE TITLE
Blog post code styling

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#251]
What's the problem?
Code samples on blog posts lack a distinct visual style that separates them from the text content, making it hard to read. 

How might we fix this?
The code is styled in a way that makes it easy to identify and separate from the post text content.

**Comment by ghislaineguerin** [comment]
Example:
![image](https://user-images.githubusercontent.com/845767/49006251-f854cd00-f168-11e8-8dc0-737e63948c75.png)

**Comment by marcoow** [comment]
I think we mainly need to make highlight.js work again - see existing blog for reference: https://simplabs.com/blog/2018/07/24/from-spa-to-pwa.html

**Comment by ghislaineguerin** [comment]
@marcoow that's even better and solves the problem 👍
