### ISSUE TITLE
Opt-in button for the download of the whitepaper - Travel Landingpage

### ISSUE THREAD

**Issue by SaeLLo** [mainmatter/mainmatter.com#2514]
We want to send furhter information to people who downloaded the whitepaper. Therefore, we need an opt-in button somehow integrated in the download form.

**Comment by marcoow** [comment]
@umbrellarocket  So this needs to be a checkbox with a label something like "Yes, Mainmatter may contact me for maketing purposes" or something – you can use a placeholder text for now

**Comment by SaeLLo** [comment]
@umbrellarocket By when can you get that done?

**Comment by umbrellarocket** [comment]
@SaeLLo Working on this today; thanks for checking in on this! I ran into some GitHub issues so had to fix them before proceeding

**Comment by marcoow** [comment]
online already
