### ISSUE TITLE
Fix `og:image`s for Rails and Elixir/Phoenix pages

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#2560]
We need to add the logos in the background – see

* https://sketch.com/s/066e539c-c206-4261-aafb-9634ab577579/a/JApmdQk?annotation=5502e002-d291-4cb8-823b-f61d8cabf79d
* https://sketch.com/s/066e539c-c206-4261-aafb-9634ab577579/a/elqWnGP?annotation=798695fb-421c-4dcc-a1a9-e170b497dd22

**Comment by IdeliaRisella** [comment]
![lp-ruby-consulting-og-image](https://github.com/user-attachments/assets/c7f251eb-fc72-4598-b7db-7c051eddcc7a)
![lp-elixir-phoenix-consulting-og-image](https://github.com/user-attachments/assets/1693f3ce-1441-44e6-b2c4-0a9683e88576)

Do you mean something like these?

**Comment by marcoow** [comment]
yes
