### ISSUE TITLE
Missing simplabs logo on link previews

### ISSUE THREAD

**Issue by oliverbarnes** [mainmatter/mainmatter.com#29]
Would be nice to have the simplabs logo where the page icon shows up:

![image](https://cloud.githubusercontent.com/assets/21290/18308292/dc446f40-74eb-11e6-9fc6-6f57789eba28.png)

**Comment by ganeshbsub** [comment]
Works now. Apparently, it needed the full path to the image in the meta tag. 

https://twitter.com/digiberber/status/773482613797445632
