### ISSUE TITLE
Refactor shape blocks

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#309]
Current classes for the shape elements on the site do not reflect their design intent or usage.

Instead of
shape left, shape right, shape-content, shape-text, shape-center etc

We will call the elements based on the following structure:

Featured Block
Wrapper
Background
Image
Caption

![image](https://user-images.githubusercontent.com/845767/55063572-88a01180-5078-11e9-9ba1-5dc2dbbb3432.png)

**Comment by pichfl** [comment]
I'm taking over here, replacing the CSS shapes with inlined SVGs.

> Current shape structure requires too many blocks. We want to simplify to one block as the blocks by themselves can't really be used. We want to style the shape component by defining states rather than combining blocks.

- [x] Blog (used as header for the blog)
- [x] Featured (used for home and case study pages)
- [x] Across (used for footer layout / expertise / community)
