### ISSUE TITLE
Create content for client highlights

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#312]
We need brief content to highlight client work on the website. It should be simple, one paragraph short descriptions of the work that was made for them.

![image](https://user-images.githubusercontent.com/845767/55142753-a7b4a700-513d-11e9-86a7-b0832930c843.png)

**Comment by marcoow** [comment]
@pichfl: I guess it doesn't make sense for me to fill in this content before you have finished the redesign of the `/work` page?

**Comment by pichfl** [comment]
I agree. I should be able to push a first update PR tonight.

**Comment by pichfl** [comment]
@marcoow the redesign should be complete, you may commence with the content updates 🙂

**Comment by marcoow** [comment]
done via #361
