### ISSUE TITLE
Page: blog posts by author

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#339]
We need a page for listing all posts by a particular author - I guess that would be the page I reach when clicking on the author's name here:

<img width="670" alt="Bildschirmfoto 2019-04-15 um 13 21 32" src="https://user-images.githubusercontent.com/1510/56128991-703d5b80-5f81-11e9-9d10-084f641a56b2.png">

**Comment by pichfl** [comment]
Mockup (Ignore the grey blocks, they are the offsets)
![Blog Posts by Author](https://user-images.githubusercontent.com/194641/56373950-65ddc480-6202-11e9-8413-e8752e633153.jpg)

**Comment by marcoow** [comment]
wouldn't it be nice to show the author's pic and short bio we have on the posts as well?

**Comment by pichfl** [comment]
Yes, totally! I don't think this is the final look and I hope @ghislaineguerin has input, but this is a functional version that should work in any case.

**Comment by ghislaineguerin** [comment]
![Blog Posts by Author](https://user-images.githubusercontent.com/845767/56722286-0c681f00-6747-11e9-87e1-fbbd73fbacd0.jpg)

**Comment by ghislaineguerin** [comment]
@pichfl updated the mockup.

**Comment by pichfl** [comment]
Works for me. @marcoow what do you think?

**Comment by marcoow** [comment]
would it make sense to move the author's photo and profile up so it's next to the title? It seems a bit disconnected to me like this.

**Comment by pichfl** [comment]
@marcoow I created a static version in this branch here: https://github.com/simplabs/simplabs.github.io/tree/new-simplabs-blog-author

Feel free to grab what you need for a proper template and remove the branch.

**Comment by marcoow** [comment]
done via #403
