### ISSUE TITLE
Imprint and Data privacy

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#359]
We should be able to re-use content from https://github.com/simplabs/simplabs.github.io/blob/master/imprint/index.html

**Comment by marcoow** [comment]
@pichfl the footer layout is broken for wide viewports: 
<img width="1343" alt="Bildschirmfoto 2019-05-10 um 16 32 46" src="https://user-images.githubusercontent.com/1510/57534923-666d0500-7341-11e9-87e2-f254a9f5b17a.png">
