### ISSUE TITLE
Tutoring Page - finishing touches

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#390]
- [ ] add cross references to other services:

<img width="141" alt="Bildschirmfoto 2019-04-30 um 16 34 28" src="https://user-images.githubusercontent.com/1510/56969863-4f226080-6b66-11e9-835a-6ea1093314ad.png">

**Comment by pichfl** [comment]
Where should those go? Should we replace the Playbook in the sidebar?

**Comment by marcoow** [comment]
I don't know. @ghislaineguerin: can you clarify?

**Comment by ghislaineguerin** [comment]
@pichfl @marcoow 
Yes, those should be placed at the bottom part of the service specific pages (the ones with the form).

**Comment by pichfl** [comment]
Doing so in their current iteration will leave a lot of empty space on the left, I'm not sure if that is desired.

**Comment by ghislaineguerin** [comment]
@pichfl more space in the left should be avoided. Ideally left is always longer than the right content. I had the same issue w/ recent blog posts. I will solve this on sketch first.

**Comment by marcoow** [comment]
We just leave these out for now and worry about it post launch.

**Comment by marcoow** [comment]
unassigning Flo as this is TODO and he's not actually working on it

**Comment by marcoow** [comment]
this is included in #389 now
