### ISSUE TITLE
Timify Case Study Page

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#393]
This page is missing and needs to be created. Find the generic cast study design here: https://share.goabstract.com/6fc98f3b-b7ee-4c1f-8ed3-0677e661f087

Updated Design:
https://share.goabstract.com/876bbfe7-4941-4d71-8a04-be2015297baa?mode=design&sha=eb721d56ee50f656216f8b27e6c920fd5243fb8c

**Comment by ghislaineguerin** [comment]
![Timify](https://user-images.githubusercontent.com/845767/57293115-07e72300-70c4-11e9-8c39-4028dbef194e.png)

**Comment by marcoow** [comment]
done via #416
