### ISSUE TITLE
Expedition Case Study Page

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#394]
This page is missing and needs to be created. Find the generic cast study design here: https://share.goabstract.com/6fc98f3b-b7ee-4c1f-8ed3-0677e661f087

UPDATED DESIGN:
https://share.goabstract.com/d77ae3eb-bbf2-430e-b11f-8afdcda212a5?mode=design&sha=66c9b3a64b43f748c0e542468d198bf07a84c1bf

**Comment by ghislaineguerin** [comment]
![image](https://user-images.githubusercontent.com/845767/57381515-61764d00-71ab-11e9-944e-82c51261977d.png)

**Comment by marcoow** [comment]
done via #418
