### ISSUE TITLE
Elixir & Phoenix Page

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#398]
This page is currently missing and needs to be created. There is no design for this yet that I am aware of.

Design is available here: https://share.goabstract.com/ce496ef4-a264-4494-b3d1-7ec36355ce0d?mode=design&sha=de4379e006ed3bb31c0b3068eb931e71f63facc0

**Comment by marcoow** [comment]
@ghislaineguerin we are now a founding sponsor of the Erlang Ecosystem Foundation - that should go on the Elixir/Phoenix page as well: https://erlef.org

**Comment by ghislaineguerin** [comment]
@marcoow got it, I will update the design.
