### ISSUE TITLE
Contact Page - finishing touches

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#408]
Currently we're only saying _"let us know how we can help you"_ - we should have some more text (maybe expendable?) that describes a bit better what happens after they send an email, e.g. _"we'll schedule a call, discuss the problem, discuss possible solutions, try and give rough estimates etc."_

- [x] build UI for the above text, fill in dummy text for now
- [x] write proper text

**Comment by pichfl** [comment]
@ghislaineguerin can you update the screen in Abstract?

**Comment by ghislaineguerin** [comment]
@pichfl @marcoow 
How about this?
https://share.goabstract.com/34dd8b52-78b9-4239-b198-42c6393009b5?mode=design&sha=8c2c32d1f0a8a6a4d8aff7284c970a423b9c320e
