### ISSUE TITLE
Create Open:Graph images for Facebook and Twitter

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#421]
> Add featured images to blog posts and create thumbnails of our talks with the highest impressions on image search (ember, pwa, glimmer)

- [x] Create templates for blog post types
- [x] Check for relevant posts and talks on Google Analytics / Search console
- [x] Create images for those
- [x] Add them to the OG image tags (`meta[name="twitter:image:src"][property="og:image"]`)

**Comment by pichfl** [comment]
Extends on #627

**Comment by ghislaineguerin** [comment]
Images will be created for the top 10 entry pages and top 10 pages with most impressions, there's an overlap between both lists.

**Most entry visits over the past 3 months:**
1. Sentry error reporting for Ember.js | Blog | simplabs
2. SPAs, PWAs and SSR | Blog | simplabs
3. From SPA to PWA | Blog | simplabs
4. actix – an actor framework for the Rust programming language | Blog | simplabs
5. Using npm libraries in Ember CLI | Blog | simplabs
6. Automated dependency updates for your internal GitLab server️ | Blog | simplabs
7. actix – a basic TCP client | Blog | simplabs
8. On Computed Properties vs. Helpers | Blog | simplabs
9. Building a PWA with Glimmer.js | Blog | simplabs
10. Assert Your Style - Testing CSS in Ember Apps | Blog | simplabs

**Most Impressions last 3 months**
1. https://simplabs.com/blog/2018/06/11/actix/
2. https://simplabs.com/blog/2018/07/24/from-spa-to-pwa/ 
3. https://simplabs.com/blog/2019/04/24/dependency-updates-for-gitlab/
4. https://simplabs.com/blog/2019/07/15/sentry-and-ember/ 
5. https://simplabs.com/blog/2017/03/21/on-computed-properties-vs-helpers/ 
6. https://simplabs.com/blog/2019/04/05/spas-pwas-and-ssr/ 
7. https://simplabs.com/blog/2018/07/03/building-a-pwa-with-glimmer-js/ 
8. https://simplabs.com/blog/2017/02/13/npm-libs-in-ember-cli/
9. https://simplabs.com/blog/2017/10/24/high-level-assertions-with-qunit-dom/ 
10. https://simplabs.com/blog/2018/12/10/assert-your-style/
