### ISSUE TITLE
Responsive navigation

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#429]
Extracted from the much too broad #357

**Comment by pichfl** [comment]
I just spent one hour wasting time trying to make this work. 
My approach was to use `window.matchMedia` to have access to media queries in JS and depending on the change event show or hide a container with the navigation. 

Note: Trying to manipulate the DOM outside the boundaries of CSSBlocks is a bad idea. 

Will continue this tomorrow.

**Comment by marcoow** [comment]
done via #430
