### ISSUE TITLE
Logos not displaying correctly on clients page on mobile devices

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#44]
On my phone the clients page doesn't render correctly:
![img_0028](https://cloud.githubusercontent.com/assets/1510/18678124/5363ecd0-7f5b-11e6-976a-afa88a0fef0d.PNG)

I assume one of the logos is too wide or so.

**Comment by ganeshbsub** [comment]
Yeah same here. This is just plain weird. I'll look into it.

**Comment by ganeshbsub** [comment]
Two logos are not links, so somehow they are differently sized.
