### ISSUE TITLE
Blog - finishing touches

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#459]
The blog is mostly fine for now but there are a few minor things open:

- [x] replace lorem ipsum in right column with some real content - maybe talks catalog with image and link to calendar as both should be relevant content in the context of the blog
- [x] the way we're showing the _"About the author"_ content now doesn't really work I think - it just looks bad; maybe we can move it below the post or something
- [x] fill in all content that was added since we branched off for the new website
- [x] remove the link on the blog post topic as we don't have #340 yet

**Comment by ghislaineguerin** [comment]
@marcoow 
about the author mockup:
https://share.goabstract.com/0c9a9053-163f-4398-9ce0-96cef8a4a01c?mode=design&sha=2e5c0c3703fe8c54b016a98981dfc55d0613def0

**Comment by marcoow** [comment]
@ghislaineguerin yes, that looks good - do you want to implement that as well?

**Comment by marcoow** [comment]
done via #527
