### ISSUE TITLE
Add effects

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#463]
We are currently missing some effects on UI elements. The only one we have for now is the hover states on buttons which is nice but there are others missing:

- [x] hover over links in header/footer
- [x] hover over arrow links
- [x] hover over plain links in body text
- others?

**Comment by pichfl** [comment]
@ghislaineguerin do you have something in mind for those?

My ideas so far:
- I'd use the simplabs blue for focus/hover on the header and footer links, but I'm not sure what the hover state for the plain links should look like.
- For the arrow links I would move the arrow ever so slightly to the right.

**Comment by ghislaineguerin** [comment]
@pichfl I think that's a good idea. As for general blue links they should show the underline when hovered over.

**Comment by marcoow** [comment]
done via #472
