### ISSUE TITLE
Nav Logo Link Alignment

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#465]
Logo link is not center-aligned with the rest of the navigation items

How it is
![image](https://user-images.githubusercontent.com/845767/58019418-c57f0680-7b05-11e9-870d-c38aa1c7642a.png)

How it should be
![image](https://user-images.githubusercontent.com/845767/58019403-bb5d0800-7b05-11e9-8c46-9cbb5a46ff17.png)

I managed to fix this by changing the display of the <a> child element to block instead of inline-block

**Comment by marcoow** [comment]
doen via #468
