### ISSUE TITLE
Add horizontal spacing between main content and sidebar

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#475]
There is currently no spacing between the main content and the sidebar which makes it look weird on narrower viewports:

<img width="1166" alt="Bildschirmfoto 2019-05-21 um 09 12 32" src="https://user-images.githubusercontent.com/1510/58075702-a5ecea00-7ba8-11e9-9117-27d00502eb4f.png">

**Comment by pichfl** [comment]
Part of the #357

**Comment by marcoow** [comment]
ok, closing this then
