### ISSUE TITLE
Add third client to /services/tutoring page

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#478]
In the client list at the bottom, we're only showing 2 clients where there should be 3:

<img width="1305" alt="Bildschirmfoto 2019-05-21 um 09 15 59" src="https://user-images.githubusercontent.com/1510/58075906-23185f00-7ba9-11e9-9a8e-56dd477efe69.png">

**Comment by pichfl** [comment]
What client would fit best?

**Comment by marcoow** [comment]
I think we wanted neighborhoodie which I renamed from `software` but apparently missed on this page: https://github.com/simplabs/simplabs.github.io/blob/new-simplabs/src/ui/components/PageTutoring/template.hbs#L95

**Comment by marcoow** [comment]
done via #506
