### ISSUE TITLE
Fix card images

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#482]
Several card images on the page don't show correctly:

* Ember page - recent blog posts: 
<img width="491" alt="Bildschirmfoto 2019-05-21 um 09 20 34" src="https://user-images.githubusercontent.com/1510/58076140-c2d5ed00-7ba9-11e9-8250-4a0cd00e1b1c.png">
* Elixir page - Elixir & Erlang Munich: 
<img width="459" alt="Bildschirmfoto 2019-05-21 um 09 21 10" src="https://user-images.githubusercontent.com/1510/58076154-cff2dc00-7ba9-11e9-8b0c-6762b2c5579c.png">
* Elixir page - recent blog posts: 
<img width="445" alt="Bildschirmfoto 2019-05-21 um 09 21 14" src="https://user-images.githubusercontent.com/1510/58076166-d719ea00-7ba9-11e9-82d6-69fab58d0937.png">

**Comment by ghislaineguerin** [comment]
@marcoow I can't reproduce this. Can you please verify?

**Comment by marcoow** [comment]
It depends on the width of the viewport - with a wider window it's sort of ok but when making the window narrower it starts to look strange. Also it doesn't affect all of the card images, e.g. on https://gallant-hawking-42050a.netlify.com/expertise/ember the EmberFest image is fine but the Ember image above the latest blog posts isn't - I guess there's something different between the 2?

**Comment by marcoow** [comment]
done via #515
