### ISSUE TITLE
Performance issue when scrolling on some pages with images in shapes

### ISSUE THREAD

**Issue by mansona** [mainmatter/mainmatter.com#486]
If you try to scroll reasonably quickly on the `/services` page you will see the page freeze for a short amount of time the first time you pass the shape with the image in the background. 

Here is a demo of the behaviour: https://cl.ly/a2fb5ebbeccc

In that video, both of the scrolls have the same "velocity" but you will see the page seem to skip the first time it is scrolled past. 

This doesn't seem to be network related i.e. I don't see anything downloading an image dynamically when we scroll to that point or anything in the network tab in chrome. It also doesn't happen on all of the pages that have this particular shape 🤔 The homepage photo of @marcoow doesn't have this issue but the `/why-simplabs` photo of me and @pichfl **does** have this issue. 

I suppose this could be related to the images not being optimised 🤔 but something to watch out for once they are if indeed this is the cause.

**Comment by pichfl** [comment]
This should go away once #443 is done. The images are way larger than they need to be, both in dimension (>4k) and file size (>1mb)

**Comment by mansona** [comment]
@pichfl yes I figured that was probably it, although I've never seen image rendering freeze up the UI thread like that 😱 Worth checking to make sure once #443 is done 👍

**Comment by pichfl** [comment]
@mansona can you check again?

**Comment by mansona** [comment]
So it is still there but it's significantly less noticeable I think we can get away with closing this issue for now. 👍
