### ISSUE TITLE
Images should use absolute paths (or we should enforce trailing / when linking internally)

### ISSUE THREAD

**Issue by mansona** [mainmatter/mainmatter.com#488]
When navigating to `/why-simplabs` internally you are able to see the picture of Jessica in the "our talks" section: 

![Screenshot 2019-05-21 at 09 43 43](https://user-images.githubusercontent.com/594890/58081437-febe8180-7bac-11e9-8756-00cd87dd240d.png)

Then I clicked "Follow simplabs on Twitter" to navigate to Twitter, and then hit **back** in the browser and now the image of Jessica doesn't show any more: 

![Screenshot 2019-05-21 at 09 45 25](https://user-images.githubusercontent.com/594890/58081555-2f062000-7bad-11e9-9fdc-717c986b5e5f.png)

I've had this issue a lot when dealing with Empress things 😂 it's caused by the fact that you can't actually go directly to the url https://gallant-hawking-42050a.netlify.com/why-simplabs (with no trailing `/`) because something in the pipeline (browser, web server etc.) is auto-filling in the trailing `/` for you. This means that the relative link to the image (that doesn't start with a `/`) is now pointing at a different location.

In this case, it seems like it's just a bug and it would need a preceding `/` for that particular link. But I would be very careful and make sure that we are not relying on relative links (for things like images in a blog post) because of this sort of behaviour with trailing `/` changing the location of the files 👍

**Comment by marcoow** [comment]
done via #502
