### ISSUE TITLE
Layout: Misaligned Client Logos on Mobile

### ISSUE THREAD

**Issue by jayjayjpg** [mainmatter/mainmatter.com#489]
The client logos on the homepage are misaligned in the mobile view. I'd expect them to not overflow the page by either being smaller or by them not being aligned next, but instead on top of each other.

### Details for Reproduction

**URL**: https://gallant-hawking-42050a.netlify.com
**Viewport Size**: 360 x 640 (dimensions for e.g. Samsung Galaxy S5)
**Browser**: Brave (Chromium)

### Sources

<img width="363" alt="Screenshot 2019-05-21 at 10 45 03" src="https://user-images.githubusercontent.com/8811742/58081753-e4d56c80-7bb5-11e9-81f4-a63ff5040c20.png">

**Comment by marcoow** [comment]
@jessica-jordan responsive layout isn't done at all yet - see #357
