### ISSUE TITLE
Layout: Overflowing Text on Homepage on Mobile

### ISSUE THREAD

**Issue by jayjayjpg** [mainmatter/mainmatter.com#490]
The text at the bottom on the homepage is overflowing the page and therefore displayed as cut-off in the mobile view. I'd expect the text to not overflow the page.

Expected text to be displayed: 

> Talk to one of our experts to find out how we can help you.

Current text displayed: 

> Talk to one of our experts to find how we can help you.
 
### Details for Reproduction

**URL**: https://gallant-hawking-42050a.netlify.com
**Viewport Size**: 360 x 640 (dimensions for e.g. Samsung Galaxy S5)
**Browser**: Brave (Chromium)

### Sources
<img width="381" alt="Screenshot 2019-05-21 at 10 52 36" src="https://user-images.githubusercontent.com/8811742/58082190-c6bc3c00-7bb6-11e9-8a99-5741c6fb2fe2.png">

**Comment by marcoow** [comment]
responsive layout isn't done at all yet - see #357
