### ISSUE TITLE
Layout: Overflowing Text on Work Page on Mobile

### ISSUE THREAD

**Issue by jayjayjpg** [mainmatter/mainmatter.com#491]
The descriptive client texts on the work page are overflowing the page and displayed as cut-off on mobile. I'd expect the text to be displayed fully and padded on both sides.

### Details for Reproduction

**URL**: https://gallant-hawking-42050a.netlify.com/work
**Viewport Size**: 375 x 667 (dimensions for e.g. IPhone 6)
**Browser**: Brave (Chromium)

### Sources

<img width="390" alt="Screenshot 2019-05-21 at 10 58 22" src="https://user-images.githubusercontent.com/8811742/58082663-bbb5db80-7bb7-11e9-9e21-bf3fca0ae499.png">

<img width="398" alt="Screenshot 2019-05-21 at 11 01 26" src="https://user-images.githubusercontent.com/8811742/58082689-cbcdbb00-7bb7-11e9-9ee1-862fdce18556.png">

<img width="399" alt="Screenshot 2019-05-21 at 11 01 48" src="https://user-images.githubusercontent.com/8811742/58082723-d9834080-7bb7-11e9-92ce-f30afa0009de.png">

**Comment by marcoow** [comment]
see #357
