### ISSUE TITLE
Large amount of wasted horizontal space on the blog index

### ISSUE THREAD

**Issue by mansona** [mainmatter/mainmatter.com#492]
This issue shows up on quite a few pages but really it's only a "problem" on `/blog` because of the length of the page and the size of some of the affected content. 

The general motif for each of the pages is a "main content" column with a "read more" aside to the right with links that we want to highlight. 

![Screenshot 2019-05-21 at 09 55 01](https://user-images.githubusercontent.com/594890/58082368-c61fa780-7bae-11e9-9787-4e46caefd624.png)

This works **very** well on most pages, and it works well at the _top_ of the `/blog` section, but once it moves past the point where the aside is visible then there is a lot of wasted space for the large majority of the page: 

![Image 2019-05-21 at 9 58 28 a m](https://user-images.githubusercontent.com/594890/58082526-18f95f00-7baf-11e9-84de-c48c747ff602.png)

This feels off, and it is definitely hampered by the lack of pagination (covered in #440). It feels particularly problematic  for some of the content items that have really long intros as they would benefit from the extra space: 

![Screenshot 2019-05-21 at 11 03 22](https://user-images.githubusercontent.com/594890/58087266-1e0edc00-7bb8-11e9-9f77-3b58dba63520.png)

### TODO

- [ ] identify some content that we could put in the sidebar in addition to the current content (don't think we'll have to prepare new content for that)
- [ ] put it there

**Comment by marcoow** [comment]
I think the page doesn't really make much sense as it is anyway due to its huge length.

**Comment by marcoow** [comment]
Most of this will be fixed by #440 but I think we can still put a bit more in the sidebar.
