### ISSUE TITLE
Typos in Expertise page

### ISSUE THREAD

**Issue by sdebarros** [mainmatter/mainmatter.com#495]
- Should be "... meetups **and** are co-organizers of ..." <img width="580" alt="Screen Shot 2019-05-21 at 14 19 28" src="https://user-images.githubusercontent.com/5116277/58099532-1e20d300-7bdc-11e9-9bd8-e7071552557d.png">

- Missing space in "coach platform.We worked" on second line, and I think the hyphen in "high - performance" on the third line is unnecessary <img width="357" alt="Screen Shot 2019-05-21 at 14 20 20" src="https://user-images.githubusercontent.com/5116277/58099816-b323cc00-7bdc-11e9-9f4e-820e24b5d7df.png">

**Comment by marcoow** [comment]
done via #503
