### ISSUE TITLE
Typo in /services/full-stack-engineering

### ISSUE THREAD

**Issue by sdebarros** [mainmatter/mainmatter.com#498]
- Should be "simplabs **has** a proven track record..." (or simplabs experts have...)
- I think the "Whether it be designing..." sounds a bit off, I'm not really sure if it's wrong, but I think it should be "Whether it is designing..." or "Be it designing..."
<img width="560" alt="Screen Shot 2019-05-21 at 15 31 41" src="https://user-images.githubusercontent.com/5116277/58100252-8fad5100-7bdd-11e9-8175-d0aa2f3d8f87.png">

**Comment by marcoow** [comment]
I think

> Whether it be designing...

was from a text that @mrmrcoleman wrote so I'd assume it's fine.

**Comment by marcoow** [comment]
done via #503
