### ISSUE TITLE
Repeated content on Homepage

### ISSUE THREAD

**Issue by sdebarros** [mainmatter/mainmatter.com#499]
Consider finding an alternative to the phrase "We turn ideas into products", it appears three times in the homepage (or a slightly different version), in one case in sections that are right next to each other.

In the case study section:
<img width="413" alt="Screen Shot 2019-05-21 at 15 40 07" src="https://user-images.githubusercontent.com/5116277/58100869-c9cb2280-7bde-11e9-9d77-535159e8483a.png">

In the services section:
<img width="629" alt="Screen Shot 2019-05-21 at 15 38 46" src="https://user-images.githubusercontent.com/5116277/58100804-aacc9080-7bde-11e9-832b-4cf9f6eac285.png">

**Comment by marcoow** [comment]
done via #503
