### ISSUE TITLE
Hovering over items in the mobile menu hides items

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#504]
…as the hover color is the same as the background color:

<img width="531" alt="Bildschirmfoto 2019-05-21 um 20 43 48" src="https://user-images.githubusercontent.com/1510/58122122-35c28080-7c09-11e9-8de4-9c2c9ca596c2.png">

Of course on mobile devices you cannot really hover anyway but as this is an easy fix, I think it'd be nice to fix it as well for narrow viewports on the desktop.

**Comment by pichfl** [comment]
Fixed in dbffb05b9111a70d65c8c94fca06b71975d9a026 of #500. Will extract.

**Comment by marcoow** [comment]
done via #512
