### ISSUE TITLE
Fix blog URLs

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#523]
The blog URLs on the current page are in the form `2019/05/10/may-monthly-update.html` but with the new page we're currently changing that to `2019-05-10-may-monthly-update/`. We should

- [x] format the date as `2019/05/10/`
- [x] redirect `2019/05/10/may-monthly-update.html` to `2019/05/10/may-monthly-update/` (Switch on Netlify's pretty URL feature)

**Comment by pichfl** [comment]
I wonder if Netlify actually does some of the work for us there - see https://www.netlify.com/docs/redirects/#trailing-slash

> In addition to forwarding paths like /about to /about/ (a common practice in static sites and single page apps), it will also rewrite paths like /about.html to /about/.

**Comment by marcoow** [comment]
Yes, that looks good indeed - I updated the description above.

**Comment by marcoow** [comment]
done via #529
