### ISSUE TITLE
Fix handling of markdown for tables

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#547]
markdown for tables is not currently handled correctly, e.g. in https://simplabs.com/blog/2017/12/04/enginification/:

<img width="1342" alt="Bildschirmfoto 2019-05-26 um 16 12 58" src="https://user-images.githubusercontent.com/1510/58382953-22c8fb00-7fd1-11e9-99d7-3618df793f7f.png">

**Comment by pichfl** [comment]
That is not a problem of the renderer (which handles tables correctly), but of the content. That table doesn't follow the Markdown specs.

```
|-------------|--------------------------------|
| Asset       | Size                           |
|-------------|--------------------------------|
| `app.js`    | 627.03 KB (117.22 KB gzipped)  |
| `vendor.js` | 1.51 MB (342.87 KB gzipped)    |
| `app.css`   | 104.31 KB (19.25 KB gzipped)   |
|-------------|--------------------------------|
```

renders as

|-------------|--------------------------------|
| Asset       | Size                           |
|-------------|--------------------------------|
| `app.js`    | 627.03 KB (117.22 KB gzipped)  |
| `vendor.js` | 1.51 MB (342.87 KB gzipped)    |
| `app.css`   | 104.31 KB (19.25 KB gzipped)   |
|-------------|--------------------------------|

vs

```
| Asset       | Size                           |
| ----------- | ------------------------------ |
| `app.js`    | 627.03 KB (117.22 KB gzipped)  |
| `vendor.js` | 1.51 MB (342.87 KB gzipped)    |
| `app.css`   | 104.31 KB (19.25 KB gzipped)   |
```

which renders correctly as

| Asset       | Size                           |
| ----------- | ------------------------------ |
| `app.js`    | 627.03 KB (117.22 KB gzipped)  |
| `vendor.js` | 1.51 MB (342.87 KB gzipped)    |
| `app.css`   | 104.31 KB (19.25 KB gzipped)   |

**Comment by marcoow** [comment]
There's another post that needs to be fixed as well: https://simplabs.com/blog/2018/11/27/open-source-maintenance
