### ISSUE TITLE
Teaser our services on the Ember page

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#552]
The purpose of the Ember Expertise page is to explain to visitors why we are the best choice if they need help with their Ember.js projects and why we have the experience and expertise that we have. As potential customers reach that page, the next step we want them to make is to either contact us or at least be interested in how we can help them. The first step for that would be to go to the _"Team Augmentation"_ or _"Tutoring"_ pages to learn more about these offerings. We should have some teasers for these pages on the Ember page so it's easy for the visitors to go there. I think we can have these teasers towards the bottom of the page as I'd expect people to look at the content of the Ember page first and then when they reach the bottom we should give them an easy way to make the next step.

### TODO

- [ ] design the teasers
- [ ] add the teasers to the Ember page (HTML/CSS)

**Comment by ghislaineguerin** [comment]
@marcoow 
https://share.goabstract.com/7ac02ea5-5dbb-4c9a-9d4a-9ccd1299b4e8?mode=design&sha=a234d1951ca26ad690383d01e8766a4ff7fbe8d1

Can I get your comments on the above. And also, if possible help with the copy. Thanks.
