### ISSUE TITLE
Menu button is hidden on some blog pages on narrow screens

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#620]
![image](https://user-images.githubusercontent.com/194641/61460616-58ee7f80-a96f-11e9-90fe-fe666c52aee4.png)

Suggested fix: Add white background or outline to the menu button to ensure it's always visible. 

We could also move the blog shape around, but I think making the menu button a bit more reliable won't hurt and the shape is actually quite interesting the way it is.

**Comment by marcoow** [comment]
@pichfl can you link some posts here that have this problem? I don't get what the problem is.

**Comment by pichfl** [comment]
Updated the title, this happens on the blog when you have a screen below 888px
