### ISSUE TITLE
Create meta description, keywords and OG tags for all pages

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#627]
@pichfl: This *won't* affect our page rank, but it makes the search results and social media embeds better, which why I would prioritize this.

- [x] Description: 160 characters or less per page. Not used for SEO directly, but improves the text below the title in search results and is used as fallback for Open Graph content (Facebook, Twitter, Slack, etc)

### Pages that need content

- [x] Home
- [x] Services
- [x] Services - Engineering
- [x] Services - Augmentation
- [x] Services - Tutoring
- [x] Expertise - Ember
- [x] Expertise - Elixir
- [x] Work
- [x] Work - Trainline
- [x] Work - Timify
- [x] Work - DDWRT
- [x] Work - Expedition
- [x] Why simplabs
- [x] Blog
- [x] Calendar
- [x] Talks
- [x] Contact us

This issue is for creating the content, implementing should be done in a separate issue.

**Comment by marcoow** [comment]
* Home

> We deliver ambitious digital products on the web and mobile devices for our clients to rely on. Our team of experts manages projects from idea to release.

* Services

> We turns ideas into products, managing projects from start to end and helps tech teams move faster with confidence via Team Augmentation and Tuturing.

* Services > Full Stack Engineering

> Our expert team guides clients through the complete project from idea to release, managing everything from concept and design to engineering and operations.

* Services > Team Augmentation

> By augmenting our clients’ engineering teams, we grow them both in numbers and capability. We will share our know-how and expertise for sustainable value.

* Services > Tutoring

> We tutor teams that approach new technologies, overcome long standing issues or struggle with delivering large scale projects on time and budget.

* Work

> simplabs has a proven track record of successful projects for international clients. We have worked with companies from small startups to big enterprises.

* Work > trainline

> Trainline is Europe’s leading rail and coach platform. We helper them deliver a high-performance mobile web app, along with an improved engineering process.

* Work > Timify

> We rebuilt Timify's MVP into a well-architected system that would be the foundation for future evolution, setting them up for sustainable long-term success.

* Work > Expedition

> simplabs helped Expedition to develop a stable and sustainable architecture, getting the most out of their technology stack based on Ember.js and Elixir.

* Work > DD-WRT

> DD-WRT is a firmware for wireless routers running on millions of devices worldwide. simplabs developed an Ember.js based foundation for a new configuration UI.

* Why simplabs

> We gather the best experts in their fields wherever they are, delivering cutting edge web apps for our clients around the world, enabling their success.

* Expertise > Ember

> simplabs are Europe's leading Ember experts with unique expertise and insights with a good part of our engineering team being on the Ember.js core team.

* Expertise > Elixir

> Elixir combines expressiveness, simplicity, performance and stability. We were early adopters of the technology and are an active member of the community.

* Contact

> Whatever you're planning, we'd love to hear more. Send us a message and we will schedule a call to understand your situation and discuss how we can help best.

* Calendar

> Find out where and when there are upcoming events, conferences and meetups we will be attending or organizing in our calendar.

* Talks

> We share our expertise and experience with others. Here are a collection of talks that our team has given at international conferences in the past years.

* Blog

> Stay on top of what's happening with our Blog. We mostly write about topics like Ember.js, Elixir, Phoenix and Progressive Web Apps as well as design and UX.

**Comment by pichfl** [comment]
@marcoow While starting with simplabs is good for the subpages, I think starting each of these descriptions might be a bit too much for the homepage. 

![image](https://user-images.githubusercontent.com/194641/62129722-b079dd00-b2d7-11e9-92d9-f287ada577a7.png)

How about this?

> Delivering ambitious digital products on the web and mobile for our clients to rely on. Our team of experts manages projects from idea to release.

**Comment by marcoow** [comment]
ah, I see - good point :+1:

**Comment by marcoow** [comment]
I added some more variation

**Comment by pichfl** [comment]
I would really drop the simplabs for the home description. Otherwise it reads 

```
simplabs
https://simplabs.com
simplabs delivers ambitious digital products on the web and mobile for our clients…
```

Otherwise I think those are really good. Should we consider pulling in a native speaker or Grammarly to check for grammar issues?

**Comment by marcoow** [comment]
Ah I see - changed 👍.

Yes, a native speaker should double-check - @mrmrcoleman, @mansona?
