### ISSUE TITLE
Using `app/app.js` in a blog post gets replaced by broccoli-asset-rev

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#630]
Turns out `broccoli-asset-rev` is really eager to replace `app/app.js`, which leads to a false positive inside our blog, more precisely inside the blog post about Sentry.

There is the `ignore` array which we could add here, where we could ignore the blog posts https://github.com/simplabs/simplabs.github.io/blob/a09082456ba63652ca9aafcf507e87b267bb4b92/ember-cli-build.js#L229-L233

I'm just not entirely sure if that might have side effects. Another option though much sneakier could be to add an invisible whitespace to the path inside the blog post.

**Comment by marcoow** [comment]
I don't see how we can easily fix this unfortunately as we cannot disable replacing for the blog content as that would also not replace anything we actually want to be replaced like image paths etc. There is no way to disable replacing on a more granular level, e.g. not replace **only** `app.js` **only** in `blog.js`.

**Comment by pichfl** [comment]
Even it it's a hack, adding a zero width whitespace to the offending string might resolve the issue for now. https://codepen.io/chriscoyier/pen/iLKwm
