### ISSUE TITLE
Investigate markdown rendering component for content pages (playbook)

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#680]
This will make editing, adding new content and the review of changes easier.

**Comment by marcoow** [comment]
How would you envision this to work (from the editor's perspective, not how the code works)?

**Comment by pichfl** [comment]
Especially for long content it would make sense to just write Markdown inside a special block that gets transpired to HTML in the compile step. Much easier to maintain than writing the html manually.

**Comment by marcoow** [comment]
I see. I'd suggest we see how much work this actually is for some time though before we build something that is potentially quite a bit of work? I feel right now we're assuming something will be annoying but we don't actually know?

**Comment by pichfl** [comment]
Of course. But if we wan't to publish the playbook properly we may want to consider something there, it's a lot of markdown content. (I wonder if we could even pull it from the other repo)

**Comment by marcoow** [comment]
Sure, that **might** be a cool thing but could be quite some work and if the playbook changes rarely (which it did in the past), would not end up being a net time-saver.

**Comment by pichfl** [comment]
True, once the dust settles, it will be some time to change this again. On to the list of nice things to have with this then.
