### ISSUE TITLE
Investigate how to apply on-scroll animations

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#702]
We want to add a little bit more dynamic to our page. To do so, we can simply animate the positions of some elements on the page and trigger those animations based on the scroll position.

To do so, we should first investigate the best option for us to do this kind of animation, what libraries to use and what actually looks decent.

TODO

- [x] Find library or code suited for our use-case
- [ ] Decide on what should be animated
- [ ] Convert these findings into a new issue for implementation

**Comment by pichfl** [comment]
#### Picks
- [laxxx](https://github.com/alexfoxy/laxxx) - includes animations and handling via data attributes
- [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) - browser support is okay for us, no external dependencies, 

#### Contenders
- [scrollama](https://github.com/russellgoldenberg/scrollama) - tiny, does not include animations
- https://github.com/janpaepke/ScrollMagic - large, even without an animation library
- https://github.com/michalsnik/aos - large, but very similar to laxxx
- https://github.com/scrollreveal/scrollreveal - one trick pony, not very interesting to us

I also tested a few others, which were either outdated or required jQuery or both. If we want to have this done quickly, laxxx or aos are interesting options, if we want to pick our animations by hand or by lifting them from libs like [Animate.css](https://github.com/daneden/animate.css), we should consider using the Intersection Observer API directly.

**Comment by marcoow** [comment]
I'd say we should definitely use `IntersectionObserver`s instead of introducing another library. The API should be supported in all of the browsers that we support and we can always fall back to not showing animations if it isn't as those are not required for correctly displaying the page but just a visual improvement.
