### ISSUE TITLE
Investigate bounce rate on blog posts

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#704]
Most of our incoming traffic is from blog posts. However, we still see a high bounce rate (>80%). As part of this issue we'll investigate whether this affects all posts, and what we could change in order to lower the rate.

**Comment by arthurp1** [comment]
It's normal to have high bounce rates on Blog posts because people are looking for quick answers. The way to improve this could be having better titles, subtitles, and having a 'Download some ebook/playbook' call to action on the bottom.
