### ISSUE TITLE
Improve layout for smaller screens

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#707]
We should improve how our website looks smaller screen such as the iPad and the MacBook Pro 13". To do so, we should reconsider and optimize our vertical rhythm and page offsets. 

Since we have all of these converted into ratios and parametric changes, we can do so by creating a single mockup for a page and everything else will fall into place automatically. There might be minor glitches, but those will be easily identified by Percy. 

To do this

- [x] Create visual mockup for a smaller base width
- [x] Consider adding another breakpoint for larger screens (based on the current measurements)
- [x] Implement the changed size values
- [x] Verify on devices

#### Shape cleanup

- [x] ShapeBlog
- [x] ShapeFeature
- [x] ShapeAcross
- [x] ShapeBold
- [x] ShapeDecorative
- [ ] ShapeWork

This is related to, but not a full successor to #439

**Comment by marcoow** [comment]
I'm closing this as the only thing that's still open is work on the shapes but those are going to change anyway.
