### ISSUE TITLE
Arrow link animation is slightly off in Safari

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#711]
The arrow link animation seems slightly off in Safari with very subtle vertical movement of the arrow which makes it look like the arrow _"jumps"_ forwards and backwards:

![bug](https://user-images.githubusercontent.com/1510/64687691-4aae7280-d48b-11e9-8bfc-b4e02283ba10.gif)

I think what we want is **horizontal movement only**.

**Comment by marcoow** [comment]
On the start page hovering over the link also moves all of the text (and the hover effect is delayed): 

![bug](https://user-images.githubusercontent.com/1510/66468157-03190780-ea86-11e9-9f85-e467219d0d87.gif)

**Comment by pichfl** [comment]
It's most likely this will be fixed when #707 is done. Blocked until then.

**Comment by marcoow** [comment]
This does still not work properly in my Safari but it does in Safari Technology Preview so I guess we can assume it to be fixed with the next release version of Safari as well. However, I'm seeing a delay before the `:hover` styles are applied in both browsers which feels bad. I'll look into fixing that.

**Comment by marcoow** [comment]
The delay is only an issue on that one shape though which is going to be replaced anyway - therefore closing this.
