### ISSUE TITLE
Ember Expertise page: Ember.js documentary video not playing in Safari

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#718]
Needs further investigation. At first glance these things become apparent:
 
- the videos url doesn't seem to be properly fingerprinted
- we should not cache the video in the service worker because of its size

Possible helpful: Safari has known issues with videos in service workers (see [here](https://adactio.com/journal/14452) for details)

**Comment by marcoow** [comment]
I checked - we're not caching the video in the service worker 👍

**Comment by pichfl** [comment]
It might help to move the `moov` atom to the front, it seems Safari has to download the whole file first. 

```
ffmpeg -i input.mp4 -movflags faststart output.mp4
```

We also might consider re-encoding the video from source, adding the shape to the video file itself.

If we do re-encode the video, remember to tick this box:
![](https://cdn-std.droplr.net/files/acc_73748/jLjSMn)
