### ISSUE TITLE
Investigate Google Search Console errors on blog content

### ISSUE THREAD

**Issue by pichfl** [mainmatter/mainmatter.com#719]
`https://simplabs.com/blog/2018/05/30/a-little-encouragement-goes-a-long-way-in-2018/` seems to have these problems:

- [x] Text too small to read
- [x] Clickable elements too close together
- [x] ~Content wider than screen~

All of the above might be resolved by #707, which improves the overall font scale

**Comment by marcoow** [comment]
this might be related to #714 as well?

**Comment by pichfl** [comment]
Turns out the first two errors were caused by an incomplete render by the Google spider. The third one was indeed related to #714 and was fixed as well.
