### ISSUE TITLE
Ember Documentary trailer display is broken in Chrome Canary

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#727]
The teaser for the documentary renders in a rectangle and isn't cut out as we intended it to be:

<img width="1366" alt="Bildschirmfoto 2019-10-24 um 09 41 29" src="https://user-images.githubusercontent.com/1510/67463924-a7807980-f642-11e9-9411-a81dd41da9ab.png">

This is in Chrome Canary.

**Comment by pichfl** [comment]
I'm unable to reproduce this in a freshly installed Version 80.0.3949.0 (Official Build) canary (64-Bit).

Looking at the image, you seem to have an old version in cache. That very frame is impossible to get with the current assets. The shape is burnt into the image and the crowd on the upper right can't ever be visible.

Are we certain the video is not cached in some way?

**Comment by marcoow** [comment]
I cleared the cache and still get it, on mobile view as well:

<img width="1366" alt="Bildschirmfoto 2019-10-24 um 11 11 38" src="https://user-images.githubusercontent.com/1510/67471077-18c62980-f64f-11e9-87bf-82f2ee19c06e.png">

**Comment by pichfl** [comment]
That is not good, looks like you're stuck with an outdated version of that asset. 

Can you disable the serviceworker and try again?

**Comment by marcoow** [comment]
hm, now it works without having changed anything:

<img width="1366" alt="Bildschirmfoto 2019-10-24 um 11 28 23" src="https://user-images.githubusercontent.com/1510/67472507-7bb8c000-f651-11e9-8b41-f8ff75940d0c.png">

Let's check this off as strange behavior in chrome canary…
