### ISSUE TITLE
Font-size is too large for wide screens

### ISSUE THREAD

**Issue by arthurp1** [mainmatter/mainmatter.com#728]
All headings, sub-headings and even the body of blog posts become unpleasant to read on screens that are wider than 1440px.

![image](https://user-images.githubusercontent.com/17333538/67474141-419ced80-f654-11e9-8df2-e5aacd01d44d.png)

**Comment by pichfl** [comment]
Will be fixed by #722

**Comment by arthurp1** [comment]
@pichfl this issue still hasn't been fixed. On both a retina mac display and a widescreen display the font sizes get way too big. Maybe set a max font size for each heading etc?
![image](https://user-images.githubusercontent.com/17333538/84368964-815e1880-abd6-11ea-8a26-527b9c89457a.png)

**Comment by arthurp1** [comment]
I think this issue has a relatively high urgency because it's impossible to read our blog posts on a large screen. @marcoow @pichfl (zoom in on the screenshots to experience this)
![image](https://user-images.githubusercontent.com/17333538/84369732-94bdb380-abd7-11ea-86c0-724eb16a9f1f.png)

**Comment by marhigh** [comment]
Let's add the following maximum font sizes: 
<img width="845" alt="Screen Shot 2020-10-13 at 13 22 07" src="https://user-images.githubusercontent.com/8226112/95854360-22acd500-0d57-11eb-8e5a-aacb8278a855.png">

These measurements were taken from the size of the fonts on the current live site at 1200 px width. Please let me know if the table above does not cover any of the existing sizes. 

Maximum font sizes can also be seen in: 
- Abstract: https://share.goabstract.com/024b6053-286d-42cc-a09b-046f8fc0c69f?collectionLayerId=198c7d88-fdfe-4838-b6ee-9f05c4a6ce92&mode=design
- Notion (where this screenshot comes from): https://www.notion.so/simplabs/Design-system-strategy-a37f5aedbcb04eff8acb32b35566a572

To ensure readability, we should also introduce a maximum line width (a max content-width) in large viewports. I will create that in a separate issue. 

Note: @pichfl suggested looking into `clamp` for this: https://css-tricks.com/linearly-scale-font-size-with-css-clamp-based-on-the-viewport/

**Comment by marcoow** [comment]
@marhigh we also need font sizes for h4 and h5 (used for example in the blog I think) – those are missing from Abstract.

**Comment by marhigh** [comment]
Please find H4 + H5 in Abstract: https://share.goabstract.com/f59c0cca-f231-49d5-bd3d-8a2455da48de

**Comment by marcoow** [comment]
fixed via #1370 and #1371
