### ISSUE TITLE
Order Workshops better

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#74]
We should order the workshops so that the frontend and backend workshops show up first (order among those doesn't really matter) and everything else comes below that (e.g. Sass, SEO etc.). Currently the SEO workshop shows up first which isn't really ideal.

**Comment by ganeshbsub** [comment]
@marcoow both of them are also categorised as "Front end Dev" based on the data from Mike North's API I think.

**Comment by marcoow** [comment]
Hm, is there any other way to identify the workshops that we'd treat as more important than other ones?

**Comment by ganeshbsub** [comment]
We'd have to manually introduce a new tag I suppose.  Don't see another way from the data that's currently available. Maybe @EmanuelaTrabaldoLena can think of something else?

**Comment by marcoow** [comment]
Hm, that's not ideal. @mike-north: is there any way we can identify the ones that are more important for us (potentially - I'm not actually sure whether that is actually true but I assume it is)?

**Comment by marcoow** [comment]
fixed by #81
