### ISSUE TITLE
[Homepage] Update header design

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#751]
**This issue is part of website revamp project**
simplabs website improvements aim to increase the ease of updating content, adding new pages, enhance content readability, and layout responsiveness.

## What needs to be done:
**Update homepage header as follows:**
<img width="1197" alt="" src="https://user-images.githubusercontent.com/845767/70151801-571e2200-16ac-11ea-9675-d595c62c7ce1.png">

### Layout
- [ ] Add a headline and sub-headline that span all columns (a)
- [ ] Add a shape container that spans all columns (b)
- [ ] Add content image and caption inside shape container (c)
- [ ] Add row of logos inside shape container (e)

### Content
- [ ] Update content based on [abstract mockup](https://share.goabstract.com/b69a3eca-2239-4585-b2f4-d7c81e52c76d?collectionLayerId=17ec6de9-653e-4e52-9426-c012b1e6b6a2&mode=design)

### Images
- [Shape content image](url)
- Logo images are already on the website

### Prerequisites
- The shape component is needed to implement this design #752

**Comment by marcoow** [comment]
@ghislaineguerin @locks is this not done already in #849? Also I think some things we decided already to do differently (e.g. not having the client logos in the shape but below it)?

**Comment by ghislaineguerin** [comment]
@marcoow  yes, this is no longer valid. I will archive.
