### ISSUE TITLE
[Homepage] Update content

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#807]
**This issue is part of website revamp project**
simplabs website improvements aim to increase the ease of updating content, adding new pages, enhance content readability, and layout responsiveness.

## What needs to be done:
**Update homepage content to include the new service sections**
![image](https://user-images.githubusercontent.com/845767/72264589-4356cb80-361b-11ea-88ba-8ac525a4c96a.png)
Links must be updated to match the new destinations.
- Digital Products "Learn More" goes to Digital Products Overview Page simplabs/services/digital-products
- Team Augmentation and Training remain the same

## Content
[ ] Replace content and links
Can be copied from the abstract file:
https://share.goabstract.com/b69a3eca-2239-4585-b2f4-d7c81e52c76d?collectionLayerId=17ec6de9-653e-4e52-9426-c012b1e6b6a2&mode=design

## Layout
The layout remains the same. Sidebar content is excluded from this issue.

**Comment by locks** [comment]
Closed by #845.
