### ISSUE TITLE
[Component] Add header variation for service pages

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#812]
**This issue is part of website revamp project**
simplabs website improvements aim to increase the ease of updating content, adding new pages, enhance content readability, and layout responsiveness.

## What needs to be done:
Create a variation for the header component that allows the new design to be implemented
![image](https://user-images.githubusercontent.com/845767/72409946-76a67100-3767-11ea-9856-825b2a2a49d3.png)

- Should allow for a full-width wrapper with different background color 
- Should include polygon shape at the bottom

**Comment by marcoow** [comment]
@ghislaineguerin we are missing the mobile designs for this still. Or do I just not know where to look?

**Comment by marcoow** [comment]
@ghislaineguerin the implementation is done so far but I need the images – marking this as blocked again

**Comment by marcoow** [comment]
done via #860
