### ISSUE TITLE
[Components] Update footer component

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#820]
**This issue is part of website revamp project**
simplabs website improvements aim to increase the ease of updating content, adding new pages, enhance content readability, and layout responsiveness.

## What needs to be done:
We need a new footer design to match the new shape design. The new footer will also include content and styling updates.

![image](https://user-images.githubusercontent.com/845767/72610091-ced7a180-3926-11ea-9508-59796672b6f6.png)

**Comment by locks** [comment]
Closed by #828.
