### ISSUE TITLE
[Component] Update work with us component to show different photos

### ISSUE THREAD

**Issue by ghislaineguerin** [mainmatter/mainmatter.com#839]
## Problem
Work with us component must display different photos of team members. Right now we are only showing Marco, but in the future we'd want to highlight more people from the team. 

## What needs to be done
The component needs to be modified so that:
- [ ] There's an attribute that allows changing the default image to other variations
- [ ] These variations are applied to different pages across the site based on a certain criteria

**Comment by arthurp1** [comment]
@ghislaineguerin I think the requirements of alternating photos are not relevant for v1 one of the updated 'Work with us' component. Having your photo on the 'Product Design' service page would be good and Marco's on the others will do for now. It looks like over-engineering.

@marcoow Can you confirm?

**Comment by marcoow** [comment]
I think this is outdated - what @ghislaineguerin builds in #828 already closes this

**Comment by locks** [comment]
Closing as #828 is merged!
