### ISSUE TITLE
Replace EmberConf announcement on start page with JSConf announcement

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#85]
…as EmberConf is over.

**Comment by trabaldini** [comment]
Is simplabs sponsoring the JSConf? Couldn't find it on the page.
Or should I change the text?

**Comment by marcoow** [comment]
Yep, we're sponsoring. We'll represent ourselves as well as Ember as a community project there. I'll send you a better text later.

**Comment by marcoow** [comment]
closed by #88
