### ISSUE TITLE
[Services] Style sidebar list in Product Development page

### ISSUE THREAD

**Issue by locks** [mainmatter/mainmatter.com#875]
## What needs to be done:
**Style the sidebar list**
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/32344/74325127-0435aa80-4d80-11ea-9b10-5967e424adfd.png">

## Design
- [ ] Implement list design. [Abstract](https://share.goabstract.com/4479af48-1f6b-4fa1-8afc-3ea396f1c9cb?mode=design&sha=25f8678b53b1a7255ad8a34bee61cf165ed93a83) file can be used as reference.

**Comment by marcoow** [comment]
done via #879
