### ISSUE TITLE
Review SEO of new pages

### ISSUE THREAD

**Issue by locks** [mainmatter/mainmatter.com#876]
- [ ] Make sure that header hierarchy is correct (no missing h2, etc)
- [ ] Add descriptions for new pages
- [ ] Make sure all new images have alt descriptions

**Comment by marcoow** [comment]
@locks I did this as part of my review of #849 and suggest we close this

**Comment by locks** [comment]
Leaving it up to @ghislaineguerin since she brought up the SEO concerns.

**Comment by locks** [comment]
Closing as addressed.
