### ISSUE TITLE
Add shaped image components

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#886]
With the new services pages we introduce a new element which is a shaped image that can appear both on the left or on the right:

<img width="592" alt="Bildschirmfoto 2020-02-14 um 12 35 48" src="https://user-images.githubusercontent.com/1510/74527669-9c6d9400-4f26-11ea-9a32-2bf4f216754a.png">

We need to add a component (or 2 components) for this that we can pass in the image we want to show and whether we want the left or right variant (or we build 2 components - one for the left and one for the right variant, depending on how much of the CSS would even be possible to share between the components). Invocation of the component should be similar to `ShapeFeature` (e.g. https://github.com/simplabs/simplabs.github.io/blob/9fde3763e97c2c65ca2348214b9937a888ad3d07/src/ui/components/ShapeFeatureTimify/template.hbs#L1) with passing `@srcset` and `@sizes` attributes.

For the implementation we can use a similar mechanism that we're also using for the [`ShapeFeature` component based on `clip-path`](https://github.com/simplabs/simplabs.github.io/blob/website-revamp/src/ui/components/ShapeFeature/stylesheet.css#L33).

## TODO

- [x] implement the component(s)
- [ ] add to the respective pages in the right places with the correct images

### How exactly are these components expected to behave on small viewports? Do they span the full viewport width? Are they adjusted left or right? [✅]

Mobile design will be addressed in https://github.com/simplabs/simplabs.github.io/issues/905.

### Which exact images are we using on which page?

TBD

## Resources

* Abstract: https://share.goabstract.com/a901d0cd-76b4-4738-b7de-01a24415be15?collectionLayerId=93d765b1-ca1a-41c8-8dbd-66b38317418f&mode=design

**Comment by ghislaineguerin** [comment]
![kanban@1600](https://user-images.githubusercontent.com/845767/76204929-98692500-61f9-11ea-8589-9cd90741c59f.jpg)
![planning@1600](https://user-images.githubusercontent.com/845767/76204937-9c954280-61f9-11ea-8ce2-66970262a429.jpg)
![wireframe@1600](https://user-images.githubusercontent.com/845767/76204940-9d2dd900-61f9-11ea-90e7-1eef53d4c6a1.jpg)
![wireframe2@1600](https://user-images.githubusercontent.com/845767/76204942-9dc66f80-61f9-11ea-9100-3ba8b32c202a.jpg)
![code@1600](https://user-images.githubusercontent.com/845767/76204952-a28b2380-61f9-11ea-9e96-8296d5ea5bd3.jpg)
![design-system@1600](https://user-images.githubusercontent.com/845767/76204964-a74fd780-61f9-11ea-83c7-9b8cd4a0bc62.jpg)
![trainline@1600](https://user-images.githubusercontent.com/845767/76204967-a8810480-61f9-11ea-9ea9-8d9c4fa4497c.jpg)

**Comment by ghislaineguerin** [comment]
![talking@1600](https://user-images.githubusercontent.com/845767/76205201-0ca3c880-61fa-11ea-8fe9-f55c23226fb4.jpg)
![team@1600](https://user-images.githubusercontent.com/845767/76205211-11687c80-61fa-11ea-8f3d-18d46f6a4f23.jpg)
![tutoring@1600](https://user-images.githubusercontent.com/845767/76205214-12011300-61fa-11ea-895a-fa94ab6d166f.jpg)

**Comment by ghislaineguerin** [comment]
![coding@1600](https://user-images.githubusercontent.com/845767/76205473-9784c300-61fa-11ea-8c57-961013e11aa4.jpg)

**Comment by ghislaineguerin** [comment]
[Archive.zip](https://github.com/simplabs/simplabs.github.io/files/4306137/Archive.zip)
@locks new pictures attached

**Comment by locks** [comment]
Thank you!

**Comment by marcoow** [comment]
@locks just to make sure there are no mis-understandings – this of course includes replacing the inline contact forms on the _"Team Augmentation"_ and _"Tutoring"_ pages with the respective shapes as per the designs.

**Comment by marcoow** [comment]
done via #898
