### ISSUE TITLE
Add Banking Innovation Forum 2020 to calendar

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#896]
I'll be speaking at the [Banking Innovation Forum 2020](https://ict-solutions-events.com/2nd-annual-international-banking-innovation-forum/) in Vienna and we should add that to our [calendar page](https://simplabs.com/calendar/).

## Contentt

* Title: _"Banking Innovation Forum 2020"_
* Date and location: _"June 18th – 19th, Vienna"_
* Text: _"The Banking Innovation Forum covers the latest trends, developments and disrupting technology that will affect The Banking Industry. Marco Otte-Witte will deliver a talk about how banks and FinTechs can leverage technology to build better products."_
* Logo: tbd

## TODO
- [ ] Add content to website
- [x] Create "logo" image for calendar item

## Open Questions

* the conference does not have a proper logo – we'll need to create something ourselves

**Comment by marcoow** [comment]
@ghislaineguerin can you come up with something that we can use in place of a proper logo to unblock this?

**Comment by ghislaineguerin** [comment]
![logo-bif](https://user-images.githubusercontent.com/845767/77730331-de4b2900-7000-11ea-9340-c106538e3bc0.png)

**Comment by ghislaineguerin** [comment]
@marcoow logo attached
