### ISSUE TITLE
Link background turns blue before navigation happens on mobile

### ISSUE THREAD

**Issue by locks** [mainmatter/mainmatter.com#911]
When clicking links, the element seems to turn selected before the navigation happens:

![Untitled 2](https://user-images.githubusercontent.com/32344/75561200-855a9600-5a3e-11ea-9321-f09ab2b6023e.gif)

We should figure out why it is happening, make sure a fix won't impact accessibility and then address it.

## Tasks
- [x] Investigate why that is happening
- [ ] Propose a fix while keeping a11y in mind

## Open Questions
- Should we disable it for all links? If we don't have `focus`/`active` styles on links it might lead to a worse accessibility experience.

**Comment by marcoow** [comment]
I cannot reproduce this in neither Safari or Chrome.

**Comment by locks** [comment]
Did you have responsive mode set to mobile? That's how I reproduced in the gif above.

**Comment by marcoow** [comment]
Isn't what you're seeing there just a visual hint that Chrome gives when simulating a mobile device?

**Comment by locks** [comment]
It is also present in actual Chrome Android. I just tried on Firefox Android and long-pressing seems to show a similar grey-colored square, but tapping doesn't.
I will block this on @ghislaineguerin confirming the bug.

**Comment by locks** [comment]
I misunderstood the bug and the current webkit tap highlight behavior will be kept.
