### ISSUE TITLE
Remove leading experts shape

### ISSUE THREAD

**Issue by locks** [mainmatter/mainmatter.com#926]
With the redesign, the leading experts shape and copy has been phased out. It should be removed from any remaining page.

![image](https://user-images.githubusercontent.com/32344/75967450-bc5bfc00-5ec3-11ea-91fe-d5154d0f6a66.png)

## Tasks
- Remove ShapeAcrossLeadingExperts from pages

**Comment by marcoow** [comment]
done via #930
