### ISSUE TITLE
Add links to Playbook page in new services pages

### ISSUE THREAD

**Issue by locks** [mainmatter/mainmatter.com#927]
Currently, the designs of Digital Products and Product design include a link to the Playbook page.
The link should be added to both pages.

<img width="691" alt="image" src="https://user-images.githubusercontent.com/32344/75981164-d6093d80-5edb-11ea-8cec-777b69debc40.png">

## Tasks
- [ ] Add Playbook link to the Digital Products page
- [ ] Add Playbook link to the Product Design page

## Resources:
- Abstract: https://share.goabstract.com/b1daea8e-7cd1-417f-8108-1b8367c018cd?mode=build&sha=37412397ea96c5a23590c63d2769fae297e8d0e7

**Comment by marcoow** [comment]
The playbook page is live already and we can add the link now: https://simplabs.com/playbook/

**Comment by locks** [comment]
Updated.

**Comment by locks** [comment]
I was working on another page and noticed that it was also missing the playbook link.

**Comment by marcoow** [comment]
done via #931
