### ISSUE TITLE
Remove "We love open source" block from product development page

### ISSUE THREAD

**Issue by locks** [mainmatter/mainmatter.com#934]
The product development page still contains a block about simplabs open source work that is removed in the redesign.

https://files.slack.com/files-pri/T024FB5V9-FUZBWUZ1D/image.png

## Tasks
- [ ] Remove the content seen in the image above from the product development page

## Resources
- Abstract: https://share.goabstract.com/06a3d7b8-8e3a-4f7d-8512-d683c96e6c85?mode=design&sha=37412397ea96c5a23590c63d2769fae297e8d0e7

**Comment by marcoow** [comment]
done via #935
