### ISSUE TITLE
Fix quote shape on Services page for mobile

### ISSUE THREAD

**Issue by locks** [mainmatter/mainmatter.com#941]
The quote shape on the Services page does not extend to the edges of the viewport and it should.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/32344/76201706-8da79380-61eb-11ea-8aac-c834ec84d7ac.png">

## Tasks
- [x] Make sure the shape touches the edges on the mobile viewport without affecting the desktop viewport

**Comment by marcoow** [comment]
done via #943
