### ISSUE TITLE
Add quote shape for Trainline

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#945]
We should add a quote shape for Trainline (same as the one for Timify introduced in #899). That shape will be shown under the team augmentation link on the _"Services"_ page:

<img width="940" alt="Bildschirmfoto 2020-03-09 um 21 06 10" src="https://user-images.githubusercontent.com/1510/76253073-43093400-624a-11ea-95b5-8604dc14cdb6.png">

The implementation of the shape will be more or less identical to the [`<ShapeQuoteTimify>` component](https://github.com/simplabs/simplabs.github.io/pull/849/files#diff-8bc0c86d4cf0704aa99eb11b1287eaea), only with different content.

### Resources

* Quote:
> We started working with simplabs to build a state-of-the-art mobile web app from the ground up and it was an absolute success! Not only are they web specialists, but their expertise in development practices and agile processes made our collaboration an absolute delight – Carl Andersson, General Manager of Trainline international
* Image: we can reuse the same image we are using for the Trainline case link that is shown on the new homepage for example: https://deploy-preview-849--objective-northcutt-37494c.netlify.com

_Originally posted by @marcoow in https://github.com/simplabs/simplabs.github.io/issues/910#issuecomment-596642151_

**Comment by locks** [comment]
Closed by #953.
