### ISSUE TITLE
Create quote component for Cardstack

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#946]
We should add a quote shape for Cardstack (same as the one for Timify introduced in #899). I suggest that to be shown above the _"What makes simplabs engineers unique?"_ section on the _"Team Augmentation"_ page:

<img width="1108" alt="Bildschirmfoto 2020-03-09 um 21 13 04" src="https://user-images.githubusercontent.com/1510/76253615-4c46d080-624b-11ea-840d-82fbda2911d5.png">

The implementation of the shape will be more or less identical to the [`<ShapeQuoteTimify>` component](https://github.com/simplabs/simplabs.github.io/pull/849/files#diff-8bc0c86d4cf0704aa99eb11b1287eaea), only with different content.

### Resources

* Quote:
> I've had the opportunity to work alongside the simplabs team on both their client-facing work for Cardstack and their open source contributions. They are experts in Ember and they are a team that takes good software-development practice seriously. – Ed Faulkner, Cardstack Lead Developer and member of the Ember.js Steering Committee
* Image: this needs to be created – we should make one similar to the ones for Timify (see quote shape [here](https://deploy-preview-849--objective-northcutt-37494c.netlify.com/services/)) and Trainline (see shape below header [here](https://deploy-preview-849--objective-northcutt-37494c.netlify.com)); We can use [this screenshot](https://assets.website-files.com/5e18083786ccdc43f2087bb2/5e3351657f2c2f40c238ee6d_R01%20Assemble.png) of their Cardstack CMS editor as that was the project we were involved with.

_Originally posted by @marcoow in https://github.com/simplabs/simplabs.github.io/issues/910#issuecomment-596646667_

**Comment by ghislaineguerin** [comment]
![cardstack@1600](https://user-images.githubusercontent.com/845767/76408236-efebca00-638c-11ea-8c2e-7dbb34bb7537.jpg)

**Comment by ghislaineguerin** [comment]
@marcoow @locks does this work for the quote image?

**Comment by marcoow** [comment]
Yes, that works 👍

**Comment by marcoow** [comment]
done via #961
