### ISSUE TITLE
Review height of images on desktop viewport

### ISSUE THREAD

**Issue by locks** [mainmatter/mainmatter.com#960]
Some of the clipped images seem to end up too short in comparison to the content to the side of them.
They should be reviewed and updated accordingly.

## Tasks
- [x] Review images sizes
- [x] Update necessary images with new sizes

**Comment by ghislaineguerin** [comment]
@locks can you post an example?

**Comment by locks** [comment]
@marcoow originally raised this issue so he should confirm, but I believe it is about this sort of inbalance where the image is shorter than the content to the side of it. Example from Team Augmentation:

![image](https://user-images.githubusercontent.com/32344/76398321-97103780-6374-11ea-8af7-afacd23c5ef4.png)

**Comment by marcoow** [comment]
Yes, I think some/most of them just are a bit too short and look strange. Also, on Abstract, they are quite a bit taller.

**Comment by marcoow** [comment]
done via #973

**Comment by ghislaineguerin** [comment]
@marcoow can we center them with the content? It will look much more balanced. I'm not sure we can replicate abstract completely as the clips are single polygons and not top/middle/bottom components like in sketch.
