### ISSUE TITLE
Improve related post shape on desktop

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#970]
We are using the `<ShapeFeature>` to link to related posts on the individual post pages in the blog. This makes sense and we should continue to do it but it doesn't really work visually on desktop:

<img width="939" alt="Bildschirmfoto 2020-03-11 um 09 46 44" src="https://user-images.githubusercontent.com/1510/76398977-1eae7400-637e-11ea-8f2b-f7c923a21ba9.png">

On mobile it's fine:

![localhost_4200_blog_2019_04_05_spas-pwas-and-ssr(iPhone X)](https://user-images.githubusercontent.com/1510/76399005-2bcb6300-637e-11ea-9803-24c8b21cf9d2.png)

### TODOs

- [ ] design  a solution for the problem (options could be adding some sort of image, arranging the text differently or using a different component altogether)
- [ ] implement that

**Comment by locks** [comment]
Possibilities:
- show image from blog post
- show author image

The shape would still need an image-less version for older blog posts, or a fallback generic image.

**Comment by marcoow** [comment]
@marhigh do we have a design for this already?

**Comment by marhigh** [comment]
@marcoow not yet, otherwise I would attach it here :) I haven't designed everything since there was very little action on this project. We can get through the ones we already have design for and in that time I can add more designs for the ones that don't.
