### ISSUE TITLE
Remove excess vertical space after blog post header

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#982]
There is excess space between each blog post's header and the subsequent paragraphs:

![post](https://user-images.githubusercontent.com/1510/76423207-b627bd00-63a6-11ea-894e-c8d86cf2f049.png)

That is due to the fact that the post's title and first paragraph are part of the `<HeaderContent>` which now have additional bottom margin. We need to override that margin with a smaller one for blog posts.

**Comment by marcoow** [comment]
done via #986

**Comment by locks** [comment]
Closed via #989.
