### ISSUE TITLE
Missing whitespace above blog shape

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#987]
The blog shape we use on the blog listing pages is missing whitespace on top. It attaches directly to the main menu button currently:

<img width="1795" alt="Bildschirmfoto 2020-03-11 um 17 29 32" src="https://user-images.githubusercontent.com/1510/76440271-e3339a00-63bd-11ea-89d0-745caf24db1d.png">

The `<HeaderContent>` has a top margin of `12rem` so adding the same top margin to the blog shape should work.

**Comment by locks** [comment]
Closed by #989.
