### ISSUE TITLE
Fix blog shape on mobile

### ISSUE THREAD

**Issue by marcoow** [mainmatter/mainmatter.com#988]
On mobile viewports, the blog shape overlays the first post's headline:

![localhost_2015_blog_](https://user-images.githubusercontent.com/1510/76440454-2aba2600-63be-11ea-91d9-c567ebf00359.png)

We need to figure out a visual solution for this and either hide it altogether or make the shape smaller, decrease the available width for the title etc.

**Comment by marhigh** [comment]
The design & spec for this is ready to go: https://share.goabstract.com/8ae826bc-280d-4975-b530-b280ecf12afd

I would suggest fixing both bugs for the shapes on the page (for both mobile and XL viewports) with this task.
