### ISSUE TITLE
Create playbook landing page

### ISSUE THREAD

**Issue by locks** [mainmatter/mainmatter.com#994]
The playbook landing page should be created in preparation of the launch of the ebook.

## Tasks
- [x] Implement layout with temporary copy and images
- [x] finalize text
- [x] finalize images

## Resources
- Abstract: https://app.abstract.com/projects/f6401950-547a-11e9-a66d-7f6f3414ea33/branches/1afa758e-8f25-4c17-a533-a71da64f6f36/commits/9a6934239623e0ff0f04d08f719e8e2fa6fea012/files/270f3779-b0f4-43d5-b3ac-9665af17512f/layers/605FBBAE-58FD-4A12-98B7-F0F8C74E5C10?collectionId=feff5db0-94ee-4236-ada1-3483c9749c27&collectionLayerId=68355f0d-fdfa-4d36-93f4-7e39f3fde339

**Comment by marcoow** [comment]
@locks I updated the issue to include tasks for the text and images as well – I can add those once you're done with the layout.

**Comment by locks** [comment]
@marcoow I tried my best to replicate the shape with the book download link, but it will need tweaking once we have the final image.
